/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkflowRunFinished type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowRunFinished{}

// WorkflowRunFinished Webhook payload for finished workflow runs.
type WorkflowRunFinished struct {
	// Workflow run ID
	Id string `json:"id"`
	// Workflow run status
	Status RunStatus `json:"status"`
}

type _WorkflowRunFinished WorkflowRunFinished

// NewWorkflowRunFinished instantiates a new WorkflowRunFinished object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowRunFinished(id string, status RunStatus) *WorkflowRunFinished {
	this := WorkflowRunFinished{}
	this.Id = id
	this.Status = status
	return &this
}

// NewWorkflowRunFinishedWithDefaults instantiates a new WorkflowRunFinished object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowRunFinishedWithDefaults() *WorkflowRunFinished {
	this := WorkflowRunFinished{}
	return &this
}

// GetId returns the Id field value
func (o *WorkflowRunFinished) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunFinished) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkflowRunFinished) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *WorkflowRunFinished) GetStatus() RunStatus {
	if o == nil {
		var ret RunStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunFinished) GetStatusOk() (*RunStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WorkflowRunFinished) SetStatus(v RunStatus) {
	o.Status = v
}

func (o WorkflowRunFinished) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowRunFinished) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *WorkflowRunFinished) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowRunFinished := _WorkflowRunFinished{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varWorkflowRunFinished)

	if err != nil {
		return err
	}

	*o = WorkflowRunFinished(varWorkflowRunFinished)

	return err
}

type NullableWorkflowRunFinished struct {
	value *WorkflowRunFinished
	isSet bool
}

func (v NullableWorkflowRunFinished) Get() *WorkflowRunFinished {
	return v.value
}

func (v *NullableWorkflowRunFinished) Set(val *WorkflowRunFinished) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowRunFinished) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowRunFinished) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowRunFinished(val *WorkflowRunFinished) *NullableWorkflowRunFinished {
	return &NullableWorkflowRunFinished{value: val, isSet: true}
}

func (v NullableWorkflowRunFinished) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowRunFinished) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
