/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// Tool - struct for Tool
type Tool struct {
	HttpCall        *HttpCall
	KnowledgeSearch *KnowledgeSearch
	Mcp             *Mcp
	PromptCall      *PromptCall
	ScriptCall      *ScriptCall
	WebSearch       *WebSearch
	WorkflowCall    *WorkflowCall
}

// HttpCallAsTool is a convenience function that returns HttpCall wrapped in Tool
func HttpCallAsTool(v *HttpCall) Tool {
	return Tool{
		HttpCall: v,
	}
}

// KnowledgeSearchAsTool is a convenience function that returns KnowledgeSearch wrapped in Tool
func KnowledgeSearchAsTool(v *KnowledgeSearch) Tool {
	return Tool{
		KnowledgeSearch: v,
	}
}

// McpAsTool is a convenience function that returns Mcp wrapped in Tool
func McpAsTool(v *Mcp) Tool {
	return Tool{
		Mcp: v,
	}
}

// PromptCallAsTool is a convenience function that returns PromptCall wrapped in Tool
func PromptCallAsTool(v *PromptCall) Tool {
	return Tool{
		PromptCall: v,
	}
}

// ScriptCallAsTool is a convenience function that returns ScriptCall wrapped in Tool
func ScriptCallAsTool(v *ScriptCall) Tool {
	return Tool{
		ScriptCall: v,
	}
}

// WebSearchAsTool is a convenience function that returns WebSearch wrapped in Tool
func WebSearchAsTool(v *WebSearch) Tool {
	return Tool{
		WebSearch: v,
	}
}

// WorkflowCallAsTool is a convenience function that returns WorkflowCall wrapped in Tool
func WorkflowCallAsTool(v *WorkflowCall) Tool {
	return Tool{
		WorkflowCall: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *Tool) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'http'
	if jsonDict["type"] == "http" {
		// try to unmarshal JSON data into HttpCall
		err = json.Unmarshal(data, &dst.HttpCall)
		if err == nil {
			return nil // data stored in dst.HttpCall, return on the first match
		} else {
			dst.HttpCall = nil
			return fmt.Errorf("failed to unmarshal Tool as HttpCall: %s", err.Error())
		}
	}

	// check if the discriminator value is 'knowledge_search'
	if jsonDict["type"] == "knowledge_search" {
		// try to unmarshal JSON data into KnowledgeSearch
		err = json.Unmarshal(data, &dst.KnowledgeSearch)
		if err == nil {
			return nil // data stored in dst.KnowledgeSearch, return on the first match
		} else {
			dst.KnowledgeSearch = nil
			return fmt.Errorf("failed to unmarshal Tool as KnowledgeSearch: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mcp'
	if jsonDict["type"] == "mcp" {
		// try to unmarshal JSON data into Mcp
		err = json.Unmarshal(data, &dst.Mcp)
		if err == nil {
			return nil // data stored in dst.Mcp, return on the first match
		} else {
			dst.Mcp = nil
			return fmt.Errorf("failed to unmarshal Tool as Mcp: %s", err.Error())
		}
	}

	// check if the discriminator value is 'prompt'
	if jsonDict["type"] == "prompt" {
		// try to unmarshal JSON data into PromptCall
		err = json.Unmarshal(data, &dst.PromptCall)
		if err == nil {
			return nil // data stored in dst.PromptCall, return on the first match
		} else {
			dst.PromptCall = nil
			return fmt.Errorf("failed to unmarshal Tool as PromptCall: %s", err.Error())
		}
	}

	// check if the discriminator value is 'script'
	if jsonDict["type"] == "script" {
		// try to unmarshal JSON data into ScriptCall
		err = json.Unmarshal(data, &dst.ScriptCall)
		if err == nil {
			return nil // data stored in dst.ScriptCall, return on the first match
		} else {
			dst.ScriptCall = nil
			return fmt.Errorf("failed to unmarshal Tool as ScriptCall: %s", err.Error())
		}
	}

	// check if the discriminator value is 'web_search'
	if jsonDict["type"] == "web_search" {
		// try to unmarshal JSON data into WebSearch
		err = json.Unmarshal(data, &dst.WebSearch)
		if err == nil {
			return nil // data stored in dst.WebSearch, return on the first match
		} else {
			dst.WebSearch = nil
			return fmt.Errorf("failed to unmarshal Tool as WebSearch: %s", err.Error())
		}
	}

	// check if the discriminator value is 'workflow'
	if jsonDict["type"] == "workflow" {
		// try to unmarshal JSON data into WorkflowCall
		err = json.Unmarshal(data, &dst.WorkflowCall)
		if err == nil {
			return nil // data stored in dst.WorkflowCall, return on the first match
		} else {
			dst.WorkflowCall = nil
			return fmt.Errorf("failed to unmarshal Tool as WorkflowCall: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Tool) MarshalJSON() ([]byte, error) {
	if src.HttpCall != nil {
		return json.Marshal(&src.HttpCall)
	}

	if src.KnowledgeSearch != nil {
		return json.Marshal(&src.KnowledgeSearch)
	}

	if src.Mcp != nil {
		return json.Marshal(&src.Mcp)
	}

	if src.PromptCall != nil {
		return json.Marshal(&src.PromptCall)
	}

	if src.ScriptCall != nil {
		return json.Marshal(&src.ScriptCall)
	}

	if src.WebSearch != nil {
		return json.Marshal(&src.WebSearch)
	}

	if src.WorkflowCall != nil {
		return json.Marshal(&src.WorkflowCall)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Tool) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.HttpCall != nil {
		return obj.HttpCall
	}

	if obj.KnowledgeSearch != nil {
		return obj.KnowledgeSearch
	}

	if obj.Mcp != nil {
		return obj.Mcp
	}

	if obj.PromptCall != nil {
		return obj.PromptCall
	}

	if obj.ScriptCall != nil {
		return obj.ScriptCall
	}

	if obj.WebSearch != nil {
		return obj.WebSearch
	}

	if obj.WorkflowCall != nil {
		return obj.WorkflowCall
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Tool) GetActualInstanceValue() interface{} {
	if obj.HttpCall != nil {
		return *obj.HttpCall
	}

	if obj.KnowledgeSearch != nil {
		return *obj.KnowledgeSearch
	}

	if obj.Mcp != nil {
		return *obj.Mcp
	}

	if obj.PromptCall != nil {
		return *obj.PromptCall
	}

	if obj.ScriptCall != nil {
		return *obj.ScriptCall
	}

	if obj.WebSearch != nil {
		return *obj.WebSearch
	}

	if obj.WorkflowCall != nil {
		return *obj.WorkflowCall
	}

	// all schemas are nil
	return nil
}

type NullableTool struct {
	value *Tool
	isSet bool
}

func (v NullableTool) Get() *Tool {
	return v.value
}

func (v *NullableTool) Set(val *Tool) {
	v.value = val
	v.isSet = true
}

func (v NullableTool) IsSet() bool {
	return v.isSet
}

func (v *NullableTool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTool(val *Tool) *NullableTool {
	return &NullableTool{value: val, isSet: true}
}

func (v NullableTool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
