/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the KnowledgeBaseFinished type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgeBaseFinished{}

// KnowledgeBaseFinished Webhook payload for finished knowledge bases.
type KnowledgeBaseFinished struct {
	// Knowledge base ID
	Id string `json:"id"`
	// Knowledge base status
	Status KnowledgeBaseStatus `json:"status"`
	// Total document count
	DocumentCount int32 `json:"documentCount"`
	// Total chunk count
	ChunkCount int32 `json:"chunkCount"`
}

type _KnowledgeBaseFinished KnowledgeBaseFinished

// NewKnowledgeBaseFinished instantiates a new KnowledgeBaseFinished object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgeBaseFinished(id string, status KnowledgeBaseStatus, documentCount int32, chunkCount int32) *KnowledgeBaseFinished {
	this := KnowledgeBaseFinished{}
	this.Id = id
	this.Status = status
	this.DocumentCount = documentCount
	this.ChunkCount = chunkCount
	return &this
}

// NewKnowledgeBaseFinishedWithDefaults instantiates a new KnowledgeBaseFinished object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgeBaseFinishedWithDefaults() *KnowledgeBaseFinished {
	this := KnowledgeBaseFinished{}
	return &this
}

// GetId returns the Id field value
func (o *KnowledgeBaseFinished) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KnowledgeBaseFinished) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KnowledgeBaseFinished) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *KnowledgeBaseFinished) GetStatus() KnowledgeBaseStatus {
	if o == nil {
		var ret KnowledgeBaseStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *KnowledgeBaseFinished) GetStatusOk() (*KnowledgeBaseStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *KnowledgeBaseFinished) SetStatus(v KnowledgeBaseStatus) {
	o.Status = v
}

// GetDocumentCount returns the DocumentCount field value
func (o *KnowledgeBaseFinished) GetDocumentCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DocumentCount
}

// GetDocumentCountOk returns a tuple with the DocumentCount field value
// and a boolean to check if the value has been set.
func (o *KnowledgeBaseFinished) GetDocumentCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentCount, true
}

// SetDocumentCount sets field value
func (o *KnowledgeBaseFinished) SetDocumentCount(v int32) {
	o.DocumentCount = v
}

// GetChunkCount returns the ChunkCount field value
func (o *KnowledgeBaseFinished) GetChunkCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChunkCount
}

// GetChunkCountOk returns a tuple with the ChunkCount field value
// and a boolean to check if the value has been set.
func (o *KnowledgeBaseFinished) GetChunkCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkCount, true
}

// SetChunkCount sets field value
func (o *KnowledgeBaseFinished) SetChunkCount(v int32) {
	o.ChunkCount = v
}

func (o KnowledgeBaseFinished) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgeBaseFinished) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["documentCount"] = o.DocumentCount
	toSerialize["chunkCount"] = o.ChunkCount
	return toSerialize, nil
}

func (o *KnowledgeBaseFinished) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"documentCount",
		"chunkCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgeBaseFinished := _KnowledgeBaseFinished{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varKnowledgeBaseFinished)

	if err != nil {
		return err
	}

	*o = KnowledgeBaseFinished(varKnowledgeBaseFinished)

	return err
}

type NullableKnowledgeBaseFinished struct {
	value *KnowledgeBaseFinished
	isSet bool
}

func (v NullableKnowledgeBaseFinished) Get() *KnowledgeBaseFinished {
	return v.value
}

func (v *NullableKnowledgeBaseFinished) Set(val *KnowledgeBaseFinished) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeBaseFinished) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeBaseFinished) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeBaseFinished(val *KnowledgeBaseFinished) *NullableKnowledgeBaseFinished {
	return &NullableKnowledgeBaseFinished{value: val, isSet: true}
}

func (v NullableKnowledgeBaseFinished) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeBaseFinished) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
