/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PromptCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptCall{}

// PromptCall Tool to invoke another prompt.
type PromptCall struct {
	// Referencing the prompt revision either by id or version number or tag.
	VersionRef VersionRef `json:"versionRef"`
	// The tool’s name.
	Name string `json:"name" validate:"regexp=[a-zA-Z0-9_-]+"`
	// The tool’s description.
	Description NullableString `json:"description,omitempty"`
	// Whether to stop processing if a tool call fails.
	FailFast *bool  `json:"failFast,omitempty"`
	Type     string `json:"type"`
}

type _PromptCall PromptCall

// NewPromptCall instantiates a new PromptCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptCall(versionRef VersionRef, name string, type_ string) *PromptCall {
	this := PromptCall{}
	this.VersionRef = versionRef
	this.Name = name
	var failFast bool = false
	this.FailFast = &failFast
	this.Type = type_
	return &this
}

// NewPromptCallWithDefaults instantiates a new PromptCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptCallWithDefaults() *PromptCall {
	this := PromptCall{}
	var failFast bool = false
	this.FailFast = &failFast
	return &this
}

// GetVersionRef returns the VersionRef field value
func (o *PromptCall) GetVersionRef() VersionRef {
	if o == nil {
		var ret VersionRef
		return ret
	}

	return o.VersionRef
}

// GetVersionRefOk returns a tuple with the VersionRef field value
// and a boolean to check if the value has been set.
func (o *PromptCall) GetVersionRefOk() (*VersionRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionRef, true
}

// SetVersionRef sets field value
func (o *PromptCall) SetVersionRef(v VersionRef) {
	o.VersionRef = v
}

// GetName returns the Name field value
func (o *PromptCall) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PromptCall) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PromptCall) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptCall) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptCall) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *PromptCall) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *PromptCall) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *PromptCall) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *PromptCall) UnsetDescription() {
	o.Description.Unset()
}

// GetFailFast returns the FailFast field value if set, zero value otherwise.
func (o *PromptCall) GetFailFast() bool {
	if o == nil || IsNil(o.FailFast) {
		var ret bool
		return ret
	}
	return *o.FailFast
}

// GetFailFastOk returns a tuple with the FailFast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptCall) GetFailFastOk() (*bool, bool) {
	if o == nil || IsNil(o.FailFast) {
		return nil, false
	}
	return o.FailFast, true
}

// HasFailFast returns a boolean if a field has been set.
func (o *PromptCall) HasFailFast() bool {
	if o != nil && !IsNil(o.FailFast) {
		return true
	}

	return false
}

// SetFailFast gets a reference to the given bool and assigns it to the FailFast field.
func (o *PromptCall) SetFailFast(v bool) {
	o.FailFast = &v
}

// GetType returns the Type field value
func (o *PromptCall) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PromptCall) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PromptCall) SetType(v string) {
	o.Type = v
}

func (o PromptCall) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["versionRef"] = o.VersionRef
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.FailFast) {
		toSerialize["failFast"] = o.FailFast
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *PromptCall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"versionRef",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptCall := _PromptCall{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPromptCall)

	if err != nil {
		return err
	}

	*o = PromptCall(varPromptCall)

	return err
}

type NullablePromptCall struct {
	value *PromptCall
	isSet bool
}

func (v NullablePromptCall) Get() *PromptCall {
	return v.value
}

func (v *NullablePromptCall) Set(val *PromptCall) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptCall) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptCall(val *PromptCall) *NullablePromptCall {
	return &NullablePromptCall{value: val, isSet: true}
}

func (v NullablePromptCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
