/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ContentMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentMessageResponse{}

// ContentMessageResponse User or assistant message.
type ContentMessageResponse struct {
	// Message direction / role.
	Role Role `json:"role"`
	// Message content.
	Content string `json:"content"`
}

type _ContentMessageResponse ContentMessageResponse

// NewContentMessageResponse instantiates a new ContentMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentMessageResponse(role Role, content string) *ContentMessageResponse {
	this := ContentMessageResponse{}
	this.Role = role
	this.Content = content
	return &this
}

// NewContentMessageResponseWithDefaults instantiates a new ContentMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentMessageResponseWithDefaults() *ContentMessageResponse {
	this := ContentMessageResponse{}
	return &this
}

// GetRole returns the Role field value
func (o *ContentMessageResponse) GetRole() Role {
	if o == nil {
		var ret Role
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ContentMessageResponse) GetRoleOk() (*Role, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ContentMessageResponse) SetRole(v Role) {
	o.Role = v
}

// GetContent returns the Content field value
func (o *ContentMessageResponse) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ContentMessageResponse) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ContentMessageResponse) SetContent(v string) {
	o.Content = v
}

func (o ContentMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *ContentMessageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentMessageResponse := _ContentMessageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varContentMessageResponse)

	if err != nil {
		return err
	}

	*o = ContentMessageResponse(varContentMessageResponse)

	return err
}

type NullableContentMessageResponse struct {
	value *ContentMessageResponse
	isSet bool
}

func (v NullableContentMessageResponse) Get() *ContentMessageResponse {
	return v.value
}

func (v *NullableContentMessageResponse) Set(val *ContentMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContentMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContentMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentMessageResponse(val *ContentMessageResponse) *NullableContentMessageResponse {
	return &NullableContentMessageResponse{value: val, isSet: true}
}

func (v NullableContentMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
