/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Citation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Citation{}

// Citation A source the model cited.
type Citation struct {
	Title string `json:"title"`
	Url   string `json:"url"`
}

type _Citation Citation

// NewCitation instantiates a new Citation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCitation(title string, url string) *Citation {
	this := Citation{}
	this.Title = title
	this.Url = url
	return &this
}

// NewCitationWithDefaults instantiates a new Citation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCitationWithDefaults() *Citation {
	this := Citation{}
	return &this
}

// GetTitle returns the Title field value
func (o *Citation) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Citation) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Citation) SetTitle(v string) {
	o.Title = v
}

// GetUrl returns the Url field value
func (o *Citation) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *Citation) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *Citation) SetUrl(v string) {
	o.Url = v
}

func (o Citation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Citation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *Citation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCitation := _Citation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCitation)

	if err != nil {
		return err
	}

	*o = Citation(varCitation)

	return err
}

type NullableCitation struct {
	value *Citation
	isSet bool
}

func (v NullableCitation) Get() *Citation {
	return v.value
}

func (v *NullableCitation) Set(val *Citation) {
	v.value = val
	v.isSet = true
}

func (v NullableCitation) IsSet() bool {
	return v.isSet
}

func (v *NullableCitation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCitation(val *Citation) *NullableCitation {
	return &NullableCitation{value: val, isSet: true}
}

func (v NullableCitation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCitation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
