/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HttpHeader type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpHeader{}

// HttpHeader struct for HttpHeader
type HttpHeader struct {
	Key   string "json:\"key\" validate:\"regexp=.*(^[A-Za-z0-9!#$%&'*+\\\\-.^_`|~]+$).*\""
	Value string `json:"value" validate:"regexp=[\\\\x20-\\\\x7E\\\\x09]*"`
}

type _HttpHeader HttpHeader

// NewHttpHeader instantiates a new HttpHeader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpHeader(key string, value string) *HttpHeader {
	this := HttpHeader{}
	this.Key = key
	this.Value = value
	return &this
}

// NewHttpHeaderWithDefaults instantiates a new HttpHeader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpHeaderWithDefaults() *HttpHeader {
	this := HttpHeader{}
	return &this
}

// GetKey returns the Key field value
func (o *HttpHeader) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *HttpHeader) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *HttpHeader) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *HttpHeader) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *HttpHeader) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *HttpHeader) SetValue(v string) {
	o.Value = v
}

func (o HttpHeader) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpHeader) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *HttpHeader) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHttpHeader := _HttpHeader{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varHttpHeader)

	if err != nil {
		return err
	}

	*o = HttpHeader(varHttpHeader)

	return err
}

type NullableHttpHeader struct {
	value *HttpHeader
	isSet bool
}

func (v NullableHttpHeader) Get() *HttpHeader {
	return v.value
}

func (v *NullableHttpHeader) Set(val *HttpHeader) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpHeader) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpHeader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpHeader(val *HttpHeader) *NullableHttpHeader {
	return &NullableHttpHeader{value: val, isSet: true}
}

func (v NullableHttpHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpHeader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
