/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// Model the model 'Model'
type Model string

// List of Model
const (
	MODEL_GPT_6_ASTRA            Model = "gpt-6-astra"
	MODEL_GPT_5_6_SOL            Model = "gpt-5.6-sol"
	MODEL_GPT_5_6_TERRA          Model = "gpt-5.6-terra"
	MODEL_GPT_5_6_LUNA           Model = "gpt-5.6-luna"
	MODEL_GPT_5_5                Model = "gpt-5.5"
	MODEL_GPT_5_5_PRO            Model = "gpt-5.5-pro"
	MODEL_GPT_5_4                Model = "gpt-5.4"
	MODEL_GPT_5_4_MINI           Model = "gpt-5.4-mini"
	MODEL_GPT_5_4_NANO           Model = "gpt-5.4-nano"
	MODEL_GPT_5_4_PRO            Model = "gpt-5.4-pro"
	MODEL_GPT_5_2                Model = "gpt-5.2"
	MODEL_GPT_5_2_PRO            Model = "gpt-5.2-pro"
	MODEL_GPT_5_1                Model = "gpt-5.1"
	MODEL_GPT_4_1                Model = "gpt-4.1"
	MODEL_GPT_4_1_MINI           Model = "gpt-4.1-mini"
	MODEL_GPT_4O                 Model = "gpt-4o"
	MODEL_GPT_4O_MINI            Model = "gpt-4o-mini"
	MODEL_GEMINI_3_1_PRO_PREVIEW Model = "gemini-3.1-pro-preview"
	MODEL_GEMINI_3_8_FLASH       Model = "gemini-3.8-flash"
	MODEL_GEMINI_3_7_FLASH       Model = "gemini-3.7-flash"
	MODEL_GEMINI_3_6_FLASH       Model = "gemini-3.6-flash"
	MODEL_GEMINI_3_5_FLASH       Model = "gemini-3.5-flash"
	MODEL_GEMINI_3_FLASH_PREVIEW Model = "gemini-3-flash-preview"
	MODEL_GEMINI_3_5_FLASH_LITE  Model = "gemini-3.5-flash-lite"
	MODEL_GEMINI_3_1_FLASH_LITE  Model = "gemini-3.1-flash-lite"
	MODEL_GEMINI_2_5_PRO         Model = "gemini-2.5-pro"
	MODEL_GEMINI_2_5_FLASH       Model = "gemini-2.5-flash"
	MODEL_GEMINI_2_5_FLASH_LITE  Model = "gemini-2.5-flash-lite"
	MODEL_CLAUDE_FABLE_5_1       Model = "claude-fable-5-1"
	MODEL_CLAUDE_FABLE_5         Model = "claude-fable-5"
	MODEL_CLAUDE_OPUS_5          Model = "claude-opus-5"
	MODEL_CLAUDE_OPUS_4_8        Model = "claude-opus-4-8"
	MODEL_CLAUDE_OPUS_4_7        Model = "claude-opus-4-7"
	MODEL_CLAUDE_OPUS_4_6        Model = "claude-opus-4-6"
	MODEL_CLAUDE_OPUS_4_5        Model = "claude-opus-4-5"
	MODEL_CLAUDE_SONNET_5        Model = "claude-sonnet-5"
	MODEL_CLAUDE_SONNET_4_6      Model = "claude-sonnet-4-6"
	MODEL_CLAUDE_SONNET_4_5      Model = "claude-sonnet-4-5"
	MODEL_CLAUDE_HAIKU_4_5       Model = "claude-haiku-4-5"
)

// All allowed values of Model enum
var AllowedModelEnumValues = []Model{
	"gpt-6-astra",
	"gpt-5.6-sol",
	"gpt-5.6-terra",
	"gpt-5.6-luna",
	"gpt-5.5",
	"gpt-5.5-pro",
	"gpt-5.4",
	"gpt-5.4-mini",
	"gpt-5.4-nano",
	"gpt-5.4-pro",
	"gpt-5.2",
	"gpt-5.2-pro",
	"gpt-5.1",
	"gpt-4.1",
	"gpt-4.1-mini",
	"gpt-4o",
	"gpt-4o-mini",
	"gemini-3.1-pro-preview",
	"gemini-3.8-flash",
	"gemini-3.7-flash",
	"gemini-3.6-flash",
	"gemini-3.5-flash",
	"gemini-3-flash-preview",
	"gemini-3.5-flash-lite",
	"gemini-3.1-flash-lite",
	"gemini-2.5-pro",
	"gemini-2.5-flash",
	"gemini-2.5-flash-lite",
	"claude-fable-5-1",
	"claude-fable-5",
	"claude-opus-5",
	"claude-opus-4-8",
	"claude-opus-4-7",
	"claude-opus-4-6",
	"claude-opus-4-5",
	"claude-sonnet-5",
	"claude-sonnet-4-6",
	"claude-sonnet-4-5",
	"claude-haiku-4-5",
}

func (v *Model) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Model(value)
	for _, existing := range AllowedModelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Model", value)
}

// NewModelFromValue returns a pointer to a valid Model
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModelFromValue(v string) (*Model, error) {
	ev := Model(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Model: valid values are %v", v, AllowedModelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Model) IsValid() bool {
	for _, existing := range AllowedModelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Model value
func (v Model) Ptr() *Model {
	return &v
}

type NullableModel struct {
	value *Model
	isSet bool
}

func (v NullableModel) Get() *Model {
	return v.value
}

func (v *NullableModel) Set(val *Model) {
	v.value = val
	v.isSet = true
}

func (v NullableModel) IsSet() bool {
	return v.isSet
}

func (v *NullableModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModel(val *Model) *NullableModel {
	return &NullableModel{value: val, isSet: true}
}

func (v NullableModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
