/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the KnowledgeBaseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgeBaseResponse{}

// KnowledgeBaseResponse Knowledge base with documents
type KnowledgeBaseResponse struct {
	// Knowledge base ID
	Id string `json:"id"`
	// Processing status
	Status KnowledgeBaseStatus `json:"status"`
	// Total number of documents
	DocumentCount int32 `json:"documentCount"`
	// Total number of chunks across all documents
	ChunkCount int32                      `json:"chunkCount"`
	Documents  []KnowledgeDocumentSummary `json:"documents"`
}

type _KnowledgeBaseResponse KnowledgeBaseResponse

// NewKnowledgeBaseResponse instantiates a new KnowledgeBaseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgeBaseResponse(id string, status KnowledgeBaseStatus, documentCount int32, chunkCount int32, documents []KnowledgeDocumentSummary) *KnowledgeBaseResponse {
	this := KnowledgeBaseResponse{}
	this.Id = id
	this.Status = status
	this.DocumentCount = documentCount
	this.ChunkCount = chunkCount
	this.Documents = documents
	return &this
}

// NewKnowledgeBaseResponseWithDefaults instantiates a new KnowledgeBaseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgeBaseResponseWithDefaults() *KnowledgeBaseResponse {
	this := KnowledgeBaseResponse{}
	return &this
}

// GetId returns the Id field value
func (o *KnowledgeBaseResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KnowledgeBaseResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KnowledgeBaseResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *KnowledgeBaseResponse) GetStatus() KnowledgeBaseStatus {
	if o == nil {
		var ret KnowledgeBaseStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *KnowledgeBaseResponse) GetStatusOk() (*KnowledgeBaseStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *KnowledgeBaseResponse) SetStatus(v KnowledgeBaseStatus) {
	o.Status = v
}

// GetDocumentCount returns the DocumentCount field value
func (o *KnowledgeBaseResponse) GetDocumentCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DocumentCount
}

// GetDocumentCountOk returns a tuple with the DocumentCount field value
// and a boolean to check if the value has been set.
func (o *KnowledgeBaseResponse) GetDocumentCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentCount, true
}

// SetDocumentCount sets field value
func (o *KnowledgeBaseResponse) SetDocumentCount(v int32) {
	o.DocumentCount = v
}

// GetChunkCount returns the ChunkCount field value
func (o *KnowledgeBaseResponse) GetChunkCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChunkCount
}

// GetChunkCountOk returns a tuple with the ChunkCount field value
// and a boolean to check if the value has been set.
func (o *KnowledgeBaseResponse) GetChunkCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkCount, true
}

// SetChunkCount sets field value
func (o *KnowledgeBaseResponse) SetChunkCount(v int32) {
	o.ChunkCount = v
}

// GetDocuments returns the Documents field value
func (o *KnowledgeBaseResponse) GetDocuments() []KnowledgeDocumentSummary {
	if o == nil {
		var ret []KnowledgeDocumentSummary
		return ret
	}

	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value
// and a boolean to check if the value has been set.
func (o *KnowledgeBaseResponse) GetDocumentsOk() ([]KnowledgeDocumentSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Documents, true
}

// SetDocuments sets field value
func (o *KnowledgeBaseResponse) SetDocuments(v []KnowledgeDocumentSummary) {
	o.Documents = v
}

func (o KnowledgeBaseResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgeBaseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["documentCount"] = o.DocumentCount
	toSerialize["chunkCount"] = o.ChunkCount
	toSerialize["documents"] = o.Documents
	return toSerialize, nil
}

func (o *KnowledgeBaseResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"documentCount",
		"chunkCount",
		"documents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgeBaseResponse := _KnowledgeBaseResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varKnowledgeBaseResponse)

	if err != nil {
		return err
	}

	*o = KnowledgeBaseResponse(varKnowledgeBaseResponse)

	return err
}

type NullableKnowledgeBaseResponse struct {
	value *KnowledgeBaseResponse
	isSet bool
}

func (v NullableKnowledgeBaseResponse) Get() *KnowledgeBaseResponse {
	return v.value
}

func (v *NullableKnowledgeBaseResponse) Set(val *KnowledgeBaseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeBaseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeBaseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeBaseResponse(val *KnowledgeBaseResponse) *NullableKnowledgeBaseResponse {
	return &NullableKnowledgeBaseResponse{value: val, isSet: true}
}

func (v NullableKnowledgeBaseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeBaseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
