/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RunCost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunCost{}

// RunCost struct for RunCost
type RunCost struct {
	Success ModelCost `json:"success"`
	Retries ModelCost `json:"retries"`
	Total   float32   `json:"total"`
}

type _RunCost RunCost

// NewRunCost instantiates a new RunCost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunCost(success ModelCost, retries ModelCost, total float32) *RunCost {
	this := RunCost{}
	this.Success = success
	this.Retries = retries
	this.Total = total
	return &this
}

// NewRunCostWithDefaults instantiates a new RunCost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunCostWithDefaults() *RunCost {
	this := RunCost{}
	return &this
}

// GetSuccess returns the Success field value
func (o *RunCost) GetSuccess() ModelCost {
	if o == nil {
		var ret ModelCost
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *RunCost) GetSuccessOk() (*ModelCost, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *RunCost) SetSuccess(v ModelCost) {
	o.Success = v
}

// GetRetries returns the Retries field value
func (o *RunCost) GetRetries() ModelCost {
	if o == nil {
		var ret ModelCost
		return ret
	}

	return o.Retries
}

// GetRetriesOk returns a tuple with the Retries field value
// and a boolean to check if the value has been set.
func (o *RunCost) GetRetriesOk() (*ModelCost, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Retries, true
}

// SetRetries sets field value
func (o *RunCost) SetRetries(v ModelCost) {
	o.Retries = v
}

// GetTotal returns the Total field value
func (o *RunCost) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *RunCost) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *RunCost) SetTotal(v float32) {
	o.Total = v
}

func (o RunCost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunCost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["retries"] = o.Retries
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *RunCost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"retries",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunCost := _RunCost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRunCost)

	if err != nil {
		return err
	}

	*o = RunCost(varRunCost)

	return err
}

type NullableRunCost struct {
	value *RunCost
	isSet bool
}

func (v NullableRunCost) Get() *RunCost {
	return v.value
}

func (v *NullableRunCost) Set(val *RunCost) {
	v.value = val
	v.isSet = true
}

func (v NullableRunCost) IsSet() bool {
	return v.isSet
}

func (v *NullableRunCost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunCost(val *RunCost) *NullableRunCost {
	return &NullableRunCost{value: val, isSet: true}
}

func (v NullableRunCost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunCost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
