/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreatePromptRunResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePromptRunResponse{}

// CreatePromptRunResponse struct for CreatePromptRunResponse
type CreatePromptRunResponse struct {
	// Prompt run ID
	Id string `json:"id"`
	// Thread ID for multi-turn runs
	Thread string `json:"thread"`
}

type _CreatePromptRunResponse CreatePromptRunResponse

// NewCreatePromptRunResponse instantiates a new CreatePromptRunResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePromptRunResponse(id string, thread string) *CreatePromptRunResponse {
	this := CreatePromptRunResponse{}
	this.Id = id
	this.Thread = thread
	return &this
}

// NewCreatePromptRunResponseWithDefaults instantiates a new CreatePromptRunResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePromptRunResponseWithDefaults() *CreatePromptRunResponse {
	this := CreatePromptRunResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreatePromptRunResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreatePromptRunResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreatePromptRunResponse) SetId(v string) {
	o.Id = v
}

// GetThread returns the Thread field value
func (o *CreatePromptRunResponse) GetThread() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Thread
}

// GetThreadOk returns a tuple with the Thread field value
// and a boolean to check if the value has been set.
func (o *CreatePromptRunResponse) GetThreadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thread, true
}

// SetThread sets field value
func (o *CreatePromptRunResponse) SetThread(v string) {
	o.Thread = v
}

func (o CreatePromptRunResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePromptRunResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["thread"] = o.Thread
	return toSerialize, nil
}

func (o *CreatePromptRunResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"thread",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePromptRunResponse := _CreatePromptRunResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCreatePromptRunResponse)

	if err != nil {
		return err
	}

	*o = CreatePromptRunResponse(varCreatePromptRunResponse)

	return err
}

type NullableCreatePromptRunResponse struct {
	value *CreatePromptRunResponse
	isSet bool
}

func (v NullableCreatePromptRunResponse) Get() *CreatePromptRunResponse {
	return v.value
}

func (v *NullableCreatePromptRunResponse) Set(val *CreatePromptRunResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePromptRunResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePromptRunResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePromptRunResponse(val *CreatePromptRunResponse) *NullableCreatePromptRunResponse {
	return &NullableCreatePromptRunResponse{value: val, isSet: true}
}

func (v NullableCreatePromptRunResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePromptRunResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
