/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PromptRunFinished type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptRunFinished{}

// PromptRunFinished Webhook payload for finished prompt runs.
type PromptRunFinished struct {
	// Prompt run ID
	Id string `json:"id"`
	// Prompt run status
	Status RunStatus `json:"status"`
}

type _PromptRunFinished PromptRunFinished

// NewPromptRunFinished instantiates a new PromptRunFinished object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptRunFinished(id string, status RunStatus) *PromptRunFinished {
	this := PromptRunFinished{}
	this.Id = id
	this.Status = status
	return &this
}

// NewPromptRunFinishedWithDefaults instantiates a new PromptRunFinished object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptRunFinishedWithDefaults() *PromptRunFinished {
	this := PromptRunFinished{}
	return &this
}

// GetId returns the Id field value
func (o *PromptRunFinished) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PromptRunFinished) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PromptRunFinished) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *PromptRunFinished) GetStatus() RunStatus {
	if o == nil {
		var ret RunStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PromptRunFinished) GetStatusOk() (*RunStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PromptRunFinished) SetStatus(v RunStatus) {
	o.Status = v
}

func (o PromptRunFinished) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptRunFinished) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *PromptRunFinished) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptRunFinished := _PromptRunFinished{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varPromptRunFinished)

	if err != nil {
		return err
	}

	*o = PromptRunFinished(varPromptRunFinished)

	return err
}

type NullablePromptRunFinished struct {
	value *PromptRunFinished
	isSet bool
}

func (v NullablePromptRunFinished) Get() *PromptRunFinished {
	return v.value
}

func (v *NullablePromptRunFinished) Set(val *PromptRunFinished) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptRunFinished) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptRunFinished) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptRunFinished(val *PromptRunFinished) *NullablePromptRunFinished {
	return &NullablePromptRunFinished{value: val, isSet: true}
}

func (v NullablePromptRunFinished) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptRunFinished) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
