/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the KnowledgeDocumentFinished type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgeDocumentFinished{}

// KnowledgeDocumentFinished Webhook payload for finished knowledge documents.
type KnowledgeDocumentFinished struct {
	// Knowledge document ID
	Id string `json:"id"`
	// Document processing status
	Status KnowledgeDocumentStatus `json:"status"`
	// Number of chunks extracted
	ChunkCount int32 `json:"chunkCount"`
}

type _KnowledgeDocumentFinished KnowledgeDocumentFinished

// NewKnowledgeDocumentFinished instantiates a new KnowledgeDocumentFinished object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgeDocumentFinished(id string, status KnowledgeDocumentStatus, chunkCount int32) *KnowledgeDocumentFinished {
	this := KnowledgeDocumentFinished{}
	this.Id = id
	this.Status = status
	this.ChunkCount = chunkCount
	return &this
}

// NewKnowledgeDocumentFinishedWithDefaults instantiates a new KnowledgeDocumentFinished object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgeDocumentFinishedWithDefaults() *KnowledgeDocumentFinished {
	this := KnowledgeDocumentFinished{}
	return &this
}

// GetId returns the Id field value
func (o *KnowledgeDocumentFinished) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentFinished) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KnowledgeDocumentFinished) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *KnowledgeDocumentFinished) GetStatus() KnowledgeDocumentStatus {
	if o == nil {
		var ret KnowledgeDocumentStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentFinished) GetStatusOk() (*KnowledgeDocumentStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *KnowledgeDocumentFinished) SetStatus(v KnowledgeDocumentStatus) {
	o.Status = v
}

// GetChunkCount returns the ChunkCount field value
func (o *KnowledgeDocumentFinished) GetChunkCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChunkCount
}

// GetChunkCountOk returns a tuple with the ChunkCount field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentFinished) GetChunkCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkCount, true
}

// SetChunkCount sets field value
func (o *KnowledgeDocumentFinished) SetChunkCount(v int32) {
	o.ChunkCount = v
}

func (o KnowledgeDocumentFinished) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgeDocumentFinished) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["chunkCount"] = o.ChunkCount
	return toSerialize, nil
}

func (o *KnowledgeDocumentFinished) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"chunkCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgeDocumentFinished := _KnowledgeDocumentFinished{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varKnowledgeDocumentFinished)

	if err != nil {
		return err
	}

	*o = KnowledgeDocumentFinished(varKnowledgeDocumentFinished)

	return err
}

type NullableKnowledgeDocumentFinished struct {
	value *KnowledgeDocumentFinished
	isSet bool
}

func (v NullableKnowledgeDocumentFinished) Get() *KnowledgeDocumentFinished {
	return v.value
}

func (v *NullableKnowledgeDocumentFinished) Set(val *KnowledgeDocumentFinished) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeDocumentFinished) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeDocumentFinished) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeDocumentFinished(val *KnowledgeDocumentFinished) *NullableKnowledgeDocumentFinished {
	return &NullableKnowledgeDocumentFinished{value: val, isSet: true}
}

func (v NullableKnowledgeDocumentFinished) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeDocumentFinished) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
