/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateWorkflowRunResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkflowRunResponse{}

// CreateWorkflowRunResponse struct for CreateWorkflowRunResponse
type CreateWorkflowRunResponse struct {
	// Workflow run ID
	Id string `json:"id"`
	// Thread ID for multi-turn runs
	Thread string `json:"thread"`
}

type _CreateWorkflowRunResponse CreateWorkflowRunResponse

// NewCreateWorkflowRunResponse instantiates a new CreateWorkflowRunResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkflowRunResponse(id string, thread string) *CreateWorkflowRunResponse {
	this := CreateWorkflowRunResponse{}
	this.Id = id
	this.Thread = thread
	return &this
}

// NewCreateWorkflowRunResponseWithDefaults instantiates a new CreateWorkflowRunResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkflowRunResponseWithDefaults() *CreateWorkflowRunResponse {
	this := CreateWorkflowRunResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateWorkflowRunResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRunResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateWorkflowRunResponse) SetId(v string) {
	o.Id = v
}

// GetThread returns the Thread field value
func (o *CreateWorkflowRunResponse) GetThread() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Thread
}

// GetThreadOk returns a tuple with the Thread field value
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRunResponse) GetThreadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thread, true
}

// SetThread sets field value
func (o *CreateWorkflowRunResponse) SetThread(v string) {
	o.Thread = v
}

func (o CreateWorkflowRunResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkflowRunResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["thread"] = o.Thread
	return toSerialize, nil
}

func (o *CreateWorkflowRunResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"thread",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWorkflowRunResponse := _CreateWorkflowRunResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWorkflowRunResponse)

	if err != nil {
		return err
	}

	*o = CreateWorkflowRunResponse(varCreateWorkflowRunResponse)

	return err
}

type NullableCreateWorkflowRunResponse struct {
	value *CreateWorkflowRunResponse
	isSet bool
}

func (v NullableCreateWorkflowRunResponse) Get() *CreateWorkflowRunResponse {
	return v.value
}

func (v *NullableCreateWorkflowRunResponse) Set(val *CreateWorkflowRunResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkflowRunResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkflowRunResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkflowRunResponse(val *CreateWorkflowRunResponse) *NullableCreateWorkflowRunResponse {
	return &NullableCreateWorkflowRunResponse{value: val, isSet: true}
}

func (v NullableCreateWorkflowRunResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkflowRunResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
