/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScriptCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptCall{}

// ScriptCall Call custom Python or JavaScript function.
type ScriptCall struct {
	// The language of the script to execute.
	Language string `json:"language"`
	// The script that this tool executes.
	Code string `json:"code"`
	// The tool’s name.
	Name string `json:"name" validate:"regexp=[a-zA-Z0-9_-]+"`
	// The tool’s description.
	Description NullableString `json:"description,omitempty"`
	// Whether to stop processing if a tool call fails.
	FailFast bool   `json:"failFast"`
	Type     string `json:"type"`
}

type _ScriptCall ScriptCall

// NewScriptCall instantiates a new ScriptCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptCall(language string, code string, name string, failFast bool, type_ string) *ScriptCall {
	this := ScriptCall{}
	this.Language = language
	this.Code = code
	this.Name = name
	this.FailFast = failFast
	this.Type = type_
	return &this
}

// NewScriptCallWithDefaults instantiates a new ScriptCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptCallWithDefaults() *ScriptCall {
	this := ScriptCall{}
	return &this
}

// GetLanguage returns the Language field value
func (o *ScriptCall) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *ScriptCall) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *ScriptCall) SetLanguage(v string) {
	o.Language = v
}

// GetCode returns the Code field value
func (o *ScriptCall) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ScriptCall) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ScriptCall) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *ScriptCall) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ScriptCall) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ScriptCall) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScriptCall) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScriptCall) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ScriptCall) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ScriptCall) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ScriptCall) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ScriptCall) UnsetDescription() {
	o.Description.Unset()
}

// GetFailFast returns the FailFast field value
func (o *ScriptCall) GetFailFast() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FailFast
}

// GetFailFastOk returns a tuple with the FailFast field value
// and a boolean to check if the value has been set.
func (o *ScriptCall) GetFailFastOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailFast, true
}

// SetFailFast sets field value
func (o *ScriptCall) SetFailFast(v bool) {
	o.FailFast = v
}

// GetType returns the Type field value
func (o *ScriptCall) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ScriptCall) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ScriptCall) SetType(v string) {
	o.Type = v
}

func (o ScriptCall) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["language"] = o.Language
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["failFast"] = o.FailFast
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ScriptCall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"language",
		"code",
		"name",
		"failFast",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScriptCall := _ScriptCall{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScriptCall)

	if err != nil {
		return err
	}

	*o = ScriptCall(varScriptCall)

	return err
}

type NullableScriptCall struct {
	value *ScriptCall
	isSet bool
}

func (v NullableScriptCall) Get() *ScriptCall {
	return v.value
}

func (v *NullableScriptCall) Set(val *ScriptCall) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptCall) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptCall(val *ScriptCall) *NullableScriptCall {
	return &NullableScriptCall{value: val, isSet: true}
}

func (v NullableScriptCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
