/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TranscriptData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranscriptData{}

// TranscriptData An emit-tool payload, in the position it was produced.
type TranscriptData struct {
	// The emit tool that produced this payload.
	Tool string `json:"tool"`
	// The payload — the tool-call arguments, verbatim.
	Payload map[string]interface{} `json:"payload"`
	Type    string                 `json:"type"`
}

type _TranscriptData TranscriptData

// NewTranscriptData instantiates a new TranscriptData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranscriptData(tool string, payload map[string]interface{}, type_ string) *TranscriptData {
	this := TranscriptData{}
	this.Tool = tool
	this.Payload = payload
	this.Type = type_
	return &this
}

// NewTranscriptDataWithDefaults instantiates a new TranscriptData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranscriptDataWithDefaults() *TranscriptData {
	this := TranscriptData{}
	return &this
}

// GetTool returns the Tool field value
func (o *TranscriptData) GetTool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tool
}

// GetToolOk returns a tuple with the Tool field value
// and a boolean to check if the value has been set.
func (o *TranscriptData) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tool, true
}

// SetTool sets field value
func (o *TranscriptData) SetTool(v string) {
	o.Tool = v
}

// GetPayload returns the Payload field value
func (o *TranscriptData) GetPayload() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *TranscriptData) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// SetPayload sets field value
func (o *TranscriptData) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetType returns the Type field value
func (o *TranscriptData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TranscriptData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TranscriptData) SetType(v string) {
	o.Type = v
}

func (o TranscriptData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranscriptData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tool"] = o.Tool
	toSerialize["payload"] = o.Payload
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TranscriptData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tool",
		"payload",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTranscriptData := _TranscriptData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTranscriptData)

	if err != nil {
		return err
	}

	*o = TranscriptData(varTranscriptData)

	return err
}

type NullableTranscriptData struct {
	value *TranscriptData
	isSet bool
}

func (v NullableTranscriptData) Get() *TranscriptData {
	return v.value
}

func (v *NullableTranscriptData) Set(val *TranscriptData) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscriptData) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscriptData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscriptData(val *TranscriptData) *NullableTranscriptData {
	return &NullableTranscriptData{value: val, isSet: true}
}

func (v NullableTranscriptData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscriptData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
