/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Emit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Emit{}

// Emit Emit a schema-validated payload: the arguments are the result.
type Emit struct {
	// JSON schema of the payload this tool emits.
	ParamsSchema string `json:"paramsSchema"`
	// The tool’s name.
	Name string `json:"name" validate:"regexp=[a-zA-Z0-9_-]+"`
	// The tool’s description.
	Description NullableString `json:"description,omitempty"`
	// Whether to stop processing if a tool call fails.
	FailFast bool   `json:"failFast"`
	Type     string `json:"type"`
}

type _Emit Emit

// NewEmit instantiates a new Emit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmit(paramsSchema string, name string, failFast bool, type_ string) *Emit {
	this := Emit{}
	this.ParamsSchema = paramsSchema
	this.Name = name
	this.FailFast = failFast
	this.Type = type_
	return &this
}

// NewEmitWithDefaults instantiates a new Emit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmitWithDefaults() *Emit {
	this := Emit{}
	return &this
}

// GetParamsSchema returns the ParamsSchema field value
func (o *Emit) GetParamsSchema() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParamsSchema
}

// GetParamsSchemaOk returns a tuple with the ParamsSchema field value
// and a boolean to check if the value has been set.
func (o *Emit) GetParamsSchemaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParamsSchema, true
}

// SetParamsSchema sets field value
func (o *Emit) SetParamsSchema(v string) {
	o.ParamsSchema = v
}

// GetName returns the Name field value
func (o *Emit) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Emit) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Emit) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Emit) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Emit) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *Emit) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *Emit) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *Emit) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *Emit) UnsetDescription() {
	o.Description.Unset()
}

// GetFailFast returns the FailFast field value
func (o *Emit) GetFailFast() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FailFast
}

// GetFailFastOk returns a tuple with the FailFast field value
// and a boolean to check if the value has been set.
func (o *Emit) GetFailFastOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailFast, true
}

// SetFailFast sets field value
func (o *Emit) SetFailFast(v bool) {
	o.FailFast = v
}

// GetType returns the Type field value
func (o *Emit) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Emit) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Emit) SetType(v string) {
	o.Type = v
}

func (o Emit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Emit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["paramsSchema"] = o.ParamsSchema
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["failFast"] = o.FailFast
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *Emit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"paramsSchema",
		"name",
		"failFast",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmit := _Emit{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varEmit)

	if err != nil {
		return err
	}

	*o = Emit(varEmit)

	return err
}

type NullableEmit struct {
	value *Emit
	isSet bool
}

func (v NullableEmit) Get() *Emit {
	return v.value
}

func (v *NullableEmit) Set(val *Emit) {
	v.value = val
	v.isSet = true
}

func (v NullableEmit) IsSet() bool {
	return v.isSet
}

func (v *NullableEmit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmit(val *Emit) *NullableEmit {
	return &NullableEmit{value: val, isSet: true}
}

func (v NullableEmit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
