/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TranscriptText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranscriptText{}

// TranscriptText A block of assistant text.
type TranscriptText struct {
	// The assistant text.
	Content string `json:"content"`
	// Sources cited in this block, deduplicated by URL. Empty unless the model cited any.
	Citations []Citation `json:"citations"`
	Type      string     `json:"type"`
}

type _TranscriptText TranscriptText

// NewTranscriptText instantiates a new TranscriptText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranscriptText(content string, citations []Citation, type_ string) *TranscriptText {
	this := TranscriptText{}
	this.Content = content
	this.Citations = citations
	this.Type = type_
	return &this
}

// NewTranscriptTextWithDefaults instantiates a new TranscriptText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranscriptTextWithDefaults() *TranscriptText {
	this := TranscriptText{}
	return &this
}

// GetContent returns the Content field value
func (o *TranscriptText) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *TranscriptText) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *TranscriptText) SetContent(v string) {
	o.Content = v
}

// GetCitations returns the Citations field value
func (o *TranscriptText) GetCitations() []Citation {
	if o == nil {
		var ret []Citation
		return ret
	}

	return o.Citations
}

// GetCitationsOk returns a tuple with the Citations field value
// and a boolean to check if the value has been set.
func (o *TranscriptText) GetCitationsOk() ([]Citation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Citations, true
}

// SetCitations sets field value
func (o *TranscriptText) SetCitations(v []Citation) {
	o.Citations = v
}

// GetType returns the Type field value
func (o *TranscriptText) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TranscriptText) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TranscriptText) SetType(v string) {
	o.Type = v
}

func (o TranscriptText) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranscriptText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	toSerialize["citations"] = o.Citations
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TranscriptText) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
		"citations",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTranscriptText := _TranscriptText{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTranscriptText)

	if err != nil {
		return err
	}

	*o = TranscriptText(varTranscriptText)

	return err
}

type NullableTranscriptText struct {
	value *TranscriptText
	isSet bool
}

func (v NullableTranscriptText) Get() *TranscriptText {
	return v.value
}

func (v *NullableTranscriptText) Set(val *TranscriptText) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscriptText) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscriptText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscriptText(val *TranscriptText) *NullableTranscriptText {
	return &NullableTranscriptText{value: val, isSet: true}
}

func (v NullableTranscriptText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscriptText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
