/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the KnowledgeDocumentSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgeDocumentSummary{}

// KnowledgeDocumentSummary Knowledge document summary (without counts)
type KnowledgeDocumentSummary struct {
	// Document ID
	Id string `json:"id"`
	// Processing status
	Status KnowledgeDocumentStatus `json:"status"`
	// Original file name
	FileName string `json:"fileName"`
	// File size in bytes
	Bytes int32 `json:"bytes"`
	// MIME type
	MimeType string `json:"mimeType"`
}

type _KnowledgeDocumentSummary KnowledgeDocumentSummary

// NewKnowledgeDocumentSummary instantiates a new KnowledgeDocumentSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgeDocumentSummary(id string, status KnowledgeDocumentStatus, fileName string, bytes int32, mimeType string) *KnowledgeDocumentSummary {
	this := KnowledgeDocumentSummary{}
	this.Id = id
	this.Status = status
	this.FileName = fileName
	this.Bytes = bytes
	this.MimeType = mimeType
	return &this
}

// NewKnowledgeDocumentSummaryWithDefaults instantiates a new KnowledgeDocumentSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgeDocumentSummaryWithDefaults() *KnowledgeDocumentSummary {
	this := KnowledgeDocumentSummary{}
	return &this
}

// GetId returns the Id field value
func (o *KnowledgeDocumentSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentSummary) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KnowledgeDocumentSummary) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *KnowledgeDocumentSummary) GetStatus() KnowledgeDocumentStatus {
	if o == nil {
		var ret KnowledgeDocumentStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentSummary) GetStatusOk() (*KnowledgeDocumentStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *KnowledgeDocumentSummary) SetStatus(v KnowledgeDocumentStatus) {
	o.Status = v
}

// GetFileName returns the FileName field value
func (o *KnowledgeDocumentSummary) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentSummary) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *KnowledgeDocumentSummary) SetFileName(v string) {
	o.FileName = v
}

// GetBytes returns the Bytes field value
func (o *KnowledgeDocumentSummary) GetBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Bytes
}

// GetBytesOk returns a tuple with the Bytes field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentSummary) GetBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bytes, true
}

// SetBytes sets field value
func (o *KnowledgeDocumentSummary) SetBytes(v int32) {
	o.Bytes = v
}

// GetMimeType returns the MimeType field value
func (o *KnowledgeDocumentSummary) GetMimeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentSummary) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MimeType, true
}

// SetMimeType sets field value
func (o *KnowledgeDocumentSummary) SetMimeType(v string) {
	o.MimeType = v
}

func (o KnowledgeDocumentSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgeDocumentSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["fileName"] = o.FileName
	toSerialize["bytes"] = o.Bytes
	toSerialize["mimeType"] = o.MimeType
	return toSerialize, nil
}

func (o *KnowledgeDocumentSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"fileName",
		"bytes",
		"mimeType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgeDocumentSummary := _KnowledgeDocumentSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varKnowledgeDocumentSummary)

	if err != nil {
		return err
	}

	*o = KnowledgeDocumentSummary(varKnowledgeDocumentSummary)

	return err
}

type NullableKnowledgeDocumentSummary struct {
	value *KnowledgeDocumentSummary
	isSet bool
}

func (v NullableKnowledgeDocumentSummary) Get() *KnowledgeDocumentSummary {
	return v.value
}

func (v *NullableKnowledgeDocumentSummary) Set(val *KnowledgeDocumentSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeDocumentSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeDocumentSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeDocumentSummary(val *KnowledgeDocumentSummary) *NullableKnowledgeDocumentSummary {
	return &NullableKnowledgeDocumentSummary{value: val, isSet: true}
}

func (v NullableKnowledgeDocumentSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeDocumentSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
