/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PromptRun type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptRun{}

// PromptRun Prompt run status and result.
type PromptRun struct {
	// Prompt run ID.
	Id string `json:"id"`
	// Current run status.
	Status RunStatus `json:"status"`
	// Timestamp when the run was created.
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the run finished. Null while the run is pending.
	FinishedAt NullableTime `json:"finishedAt,omitempty"`
	// LLM output text produced so far; read `status` for completeness. Null when the run failed, or when the model returned no text — e.g. a turn that was only tool calls or only reasoning.
	Output NullableString `json:"output,omitempty"`
	// Payloads produced by emit tools during this run, in call order. Empty until the run completes.
	Emitted []EmittedItem `json:"emitted"`
	// The run as a renderable sequence: assistant text, the tools it used, and emit payloads in position. Empty until the run completes. `output` remains the flat text for callers that only need the answer.
	Transcript []TranscriptItem `json:"transcript"`
	// Error message from the latest failed attempt, kept even once a retry recovers — so a pending or completed run can carry one. Read `status` for the outcome.
	Error NullableString `json:"error,omitempty"`
	// Token usage accumulated over successful turns — a run that failed later still reports the earlier ones. Null until the first turn succeeds.
	TokenUsage NullableTokenUsage `json:"tokenUsage,omitempty"`
	// Cost breakdown for the run. Null while pending, or when no published rate covers the run.
	Cost NullableRunCost `json:"cost,omitempty"`
}

type _PromptRun PromptRun

// NewPromptRun instantiates a new PromptRun object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptRun(id string, status RunStatus, createdAt time.Time, emitted []EmittedItem, transcript []TranscriptItem) *PromptRun {
	this := PromptRun{}
	this.Id = id
	this.Status = status
	this.CreatedAt = createdAt
	this.Emitted = emitted
	this.Transcript = transcript
	return &this
}

// NewPromptRunWithDefaults instantiates a new PromptRun object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptRunWithDefaults() *PromptRun {
	this := PromptRun{}
	return &this
}

// GetId returns the Id field value
func (o *PromptRun) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PromptRun) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PromptRun) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *PromptRun) GetStatus() RunStatus {
	if o == nil {
		var ret RunStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PromptRun) GetStatusOk() (*RunStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PromptRun) SetStatus(v RunStatus) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PromptRun) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PromptRun) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PromptRun) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptRun) GetFinishedAt() time.Time {
	if o == nil || IsNil(o.FinishedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt.Get()
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRun) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FinishedAt.Get(), o.FinishedAt.IsSet()
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *PromptRun) HasFinishedAt() bool {
	if o != nil && o.FinishedAt.IsSet() {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given NullableTime and assigns it to the FinishedAt field.
func (o *PromptRun) SetFinishedAt(v time.Time) {
	o.FinishedAt.Set(&v)
}

// SetFinishedAtNil sets the value for FinishedAt to be an explicit nil
func (o *PromptRun) SetFinishedAtNil() {
	o.FinishedAt.Set(nil)
}

// UnsetFinishedAt ensures that no value is present for FinishedAt, not even an explicit nil
func (o *PromptRun) UnsetFinishedAt() {
	o.FinishedAt.Unset()
}

// GetOutput returns the Output field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptRun) GetOutput() string {
	if o == nil || IsNil(o.Output.Get()) {
		var ret string
		return ret
	}
	return *o.Output.Get()
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRun) GetOutputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Output.Get(), o.Output.IsSet()
}

// HasOutput returns a boolean if a field has been set.
func (o *PromptRun) HasOutput() bool {
	if o != nil && o.Output.IsSet() {
		return true
	}

	return false
}

// SetOutput gets a reference to the given NullableString and assigns it to the Output field.
func (o *PromptRun) SetOutput(v string) {
	o.Output.Set(&v)
}

// SetOutputNil sets the value for Output to be an explicit nil
func (o *PromptRun) SetOutputNil() {
	o.Output.Set(nil)
}

// UnsetOutput ensures that no value is present for Output, not even an explicit nil
func (o *PromptRun) UnsetOutput() {
	o.Output.Unset()
}

// GetEmitted returns the Emitted field value
func (o *PromptRun) GetEmitted() []EmittedItem {
	if o == nil {
		var ret []EmittedItem
		return ret
	}

	return o.Emitted
}

// GetEmittedOk returns a tuple with the Emitted field value
// and a boolean to check if the value has been set.
func (o *PromptRun) GetEmittedOk() ([]EmittedItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emitted, true
}

// SetEmitted sets field value
func (o *PromptRun) SetEmitted(v []EmittedItem) {
	o.Emitted = v
}

// GetTranscript returns the Transcript field value
func (o *PromptRun) GetTranscript() []TranscriptItem {
	if o == nil {
		var ret []TranscriptItem
		return ret
	}

	return o.Transcript
}

// GetTranscriptOk returns a tuple with the Transcript field value
// and a boolean to check if the value has been set.
func (o *PromptRun) GetTranscriptOk() ([]TranscriptItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transcript, true
}

// SetTranscript sets field value
func (o *PromptRun) SetTranscript(v []TranscriptItem) {
	o.Transcript = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptRun) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRun) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *PromptRun) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *PromptRun) SetError(v string) {
	o.Error.Set(&v)
}

// SetErrorNil sets the value for Error to be an explicit nil
func (o *PromptRun) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *PromptRun) UnsetError() {
	o.Error.Unset()
}

// GetTokenUsage returns the TokenUsage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptRun) GetTokenUsage() TokenUsage {
	if o == nil || IsNil(o.TokenUsage.Get()) {
		var ret TokenUsage
		return ret
	}
	return *o.TokenUsage.Get()
}

// GetTokenUsageOk returns a tuple with the TokenUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRun) GetTokenUsageOk() (*TokenUsage, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenUsage.Get(), o.TokenUsage.IsSet()
}

// HasTokenUsage returns a boolean if a field has been set.
func (o *PromptRun) HasTokenUsage() bool {
	if o != nil && o.TokenUsage.IsSet() {
		return true
	}

	return false
}

// SetTokenUsage gets a reference to the given NullableTokenUsage and assigns it to the TokenUsage field.
func (o *PromptRun) SetTokenUsage(v TokenUsage) {
	o.TokenUsage.Set(&v)
}

// SetTokenUsageNil sets the value for TokenUsage to be an explicit nil
func (o *PromptRun) SetTokenUsageNil() {
	o.TokenUsage.Set(nil)
}

// UnsetTokenUsage ensures that no value is present for TokenUsage, not even an explicit nil
func (o *PromptRun) UnsetTokenUsage() {
	o.TokenUsage.Unset()
}

// GetCost returns the Cost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptRun) GetCost() RunCost {
	if o == nil || IsNil(o.Cost.Get()) {
		var ret RunCost
		return ret
	}
	return *o.Cost.Get()
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRun) GetCostOk() (*RunCost, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cost.Get(), o.Cost.IsSet()
}

// HasCost returns a boolean if a field has been set.
func (o *PromptRun) HasCost() bool {
	if o != nil && o.Cost.IsSet() {
		return true
	}

	return false
}

// SetCost gets a reference to the given NullableRunCost and assigns it to the Cost field.
func (o *PromptRun) SetCost(v RunCost) {
	o.Cost.Set(&v)
}

// SetCostNil sets the value for Cost to be an explicit nil
func (o *PromptRun) SetCostNil() {
	o.Cost.Set(nil)
}

// UnsetCost ensures that no value is present for Cost, not even an explicit nil
func (o *PromptRun) UnsetCost() {
	o.Cost.Unset()
}

func (o PromptRun) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptRun) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["createdAt"] = o.CreatedAt
	if o.FinishedAt.IsSet() {
		toSerialize["finishedAt"] = o.FinishedAt.Get()
	}
	if o.Output.IsSet() {
		toSerialize["output"] = o.Output.Get()
	}
	toSerialize["emitted"] = o.Emitted
	toSerialize["transcript"] = o.Transcript
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.TokenUsage.IsSet() {
		toSerialize["tokenUsage"] = o.TokenUsage.Get()
	}
	if o.Cost.IsSet() {
		toSerialize["cost"] = o.Cost.Get()
	}
	return toSerialize, nil
}

func (o *PromptRun) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"createdAt",
		"emitted",
		"transcript",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptRun := _PromptRun{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPromptRun)

	if err != nil {
		return err
	}

	*o = PromptRun(varPromptRun)

	return err
}

type NullablePromptRun struct {
	value *PromptRun
	isSet bool
}

func (v NullablePromptRun) Get() *PromptRun {
	return v.value
}

func (v *NullablePromptRun) Set(val *PromptRun) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptRun) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptRun) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptRun(val *PromptRun) *NullablePromptRun {
	return &NullablePromptRun{value: val, isSet: true}
}

func (v NullablePromptRun) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptRun) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
