/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// ResponseFormat - struct for ResponseFormat
type ResponseFormat struct {
	JsonObjectFormat *JsonObjectFormat
	JsonSchemaFormat *JsonSchemaFormat
	TextFormat       *TextFormat
}

// JsonObjectFormatAsResponseFormat is a convenience function that returns JsonObjectFormat wrapped in ResponseFormat
func JsonObjectFormatAsResponseFormat(v *JsonObjectFormat) ResponseFormat {
	return ResponseFormat{
		JsonObjectFormat: v,
	}
}

// JsonSchemaFormatAsResponseFormat is a convenience function that returns JsonSchemaFormat wrapped in ResponseFormat
func JsonSchemaFormatAsResponseFormat(v *JsonSchemaFormat) ResponseFormat {
	return ResponseFormat{
		JsonSchemaFormat: v,
	}
}

// TextFormatAsResponseFormat is a convenience function that returns TextFormat wrapped in ResponseFormat
func TextFormatAsResponseFormat(v *TextFormat) ResponseFormat {
	return ResponseFormat{
		TextFormat: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ResponseFormat) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'json_object'
	if jsonDict["type"] == "json_object" {
		// try to unmarshal JSON data into JsonObjectFormat
		err = json.Unmarshal(data, &dst.JsonObjectFormat)
		if err == nil {
			return nil // data stored in dst.JsonObjectFormat, return on the first match
		} else {
			dst.JsonObjectFormat = nil
			return fmt.Errorf("failed to unmarshal ResponseFormat as JsonObjectFormat: %s", err.Error())
		}
	}

	// check if the discriminator value is 'json_schema'
	if jsonDict["type"] == "json_schema" {
		// try to unmarshal JSON data into JsonSchemaFormat
		err = json.Unmarshal(data, &dst.JsonSchemaFormat)
		if err == nil {
			return nil // data stored in dst.JsonSchemaFormat, return on the first match
		} else {
			dst.JsonSchemaFormat = nil
			return fmt.Errorf("failed to unmarshal ResponseFormat as JsonSchemaFormat: %s", err.Error())
		}
	}

	// check if the discriminator value is 'text'
	if jsonDict["type"] == "text" {
		// try to unmarshal JSON data into TextFormat
		err = json.Unmarshal(data, &dst.TextFormat)
		if err == nil {
			return nil // data stored in dst.TextFormat, return on the first match
		} else {
			dst.TextFormat = nil
			return fmt.Errorf("failed to unmarshal ResponseFormat as TextFormat: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ResponseFormat) MarshalJSON() ([]byte, error) {
	if src.JsonObjectFormat != nil {
		return json.Marshal(&src.JsonObjectFormat)
	}

	if src.JsonSchemaFormat != nil {
		return json.Marshal(&src.JsonSchemaFormat)
	}

	if src.TextFormat != nil {
		return json.Marshal(&src.TextFormat)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ResponseFormat) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.JsonObjectFormat != nil {
		return obj.JsonObjectFormat
	}

	if obj.JsonSchemaFormat != nil {
		return obj.JsonSchemaFormat
	}

	if obj.TextFormat != nil {
		return obj.TextFormat
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ResponseFormat) GetActualInstanceValue() interface{} {
	if obj.JsonObjectFormat != nil {
		return *obj.JsonObjectFormat
	}

	if obj.JsonSchemaFormat != nil {
		return *obj.JsonSchemaFormat
	}

	if obj.TextFormat != nil {
		return *obj.TextFormat
	}

	// all schemas are nil
	return nil
}

type NullableResponseFormat struct {
	value *ResponseFormat
	isSet bool
}

func (v NullableResponseFormat) Get() *ResponseFormat {
	return v.value
}

func (v *NullableResponseFormat) Set(val *ResponseFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseFormat(val *ResponseFormat) *NullableResponseFormat {
	return &NullableResponseFormat{value: val, isSet: true}
}

func (v NullableResponseFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
