/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// ToolStatus the model 'ToolStatus'
type ToolStatus string

// List of ToolStatus
const (
	TOOLSTATUS_OK      ToolStatus = "ok"
	TOOLSTATUS_ERROR   ToolStatus = "error"
	TOOLSTATUS_PENDING ToolStatus = "pending"
)

// All allowed values of ToolStatus enum
var AllowedToolStatusEnumValues = []ToolStatus{
	"ok",
	"error",
	"pending",
}

func (v *ToolStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ToolStatus(value)
	for _, existing := range AllowedToolStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ToolStatus", value)
}

// NewToolStatusFromValue returns a pointer to a valid ToolStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewToolStatusFromValue(v string) (*ToolStatus, error) {
	ev := ToolStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ToolStatus: valid values are %v", v, AllowedToolStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ToolStatus) IsValid() bool {
	for _, existing := range AllowedToolStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ToolStatus value
func (v ToolStatus) Ptr() *ToolStatus {
	return &v
}

type NullableToolStatus struct {
	value *ToolStatus
	isSet bool
}

func (v NullableToolStatus) Get() *ToolStatus {
	return v.value
}

func (v *NullableToolStatus) Set(val *ToolStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableToolStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableToolStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolStatus(val *ToolStatus) *NullableToolStatus {
	return &NullableToolStatus{value: val, isSet: true}
}

func (v NullableToolStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
