/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VersionRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionRef{}

// VersionRef A reference to a revision.
type VersionRef struct {
	// Definition – prompt or workflow – ID.
	DefinitionId string            `json:"definitionId"`
	IdOrTag      VersionRefIdOrTag `json:"idOrTag"`
}

type _VersionRef VersionRef

// NewVersionRef instantiates a new VersionRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionRef(definitionId string, idOrTag VersionRefIdOrTag) *VersionRef {
	this := VersionRef{}
	this.DefinitionId = definitionId
	this.IdOrTag = idOrTag
	return &this
}

// NewVersionRefWithDefaults instantiates a new VersionRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionRefWithDefaults() *VersionRef {
	this := VersionRef{}
	return &this
}

// GetDefinitionId returns the DefinitionId field value
func (o *VersionRef) GetDefinitionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefinitionId
}

// GetDefinitionIdOk returns a tuple with the DefinitionId field value
// and a boolean to check if the value has been set.
func (o *VersionRef) GetDefinitionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinitionId, true
}

// SetDefinitionId sets field value
func (o *VersionRef) SetDefinitionId(v string) {
	o.DefinitionId = v
}

// GetIdOrTag returns the IdOrTag field value
func (o *VersionRef) GetIdOrTag() VersionRefIdOrTag {
	if o == nil {
		var ret VersionRefIdOrTag
		return ret
	}

	return o.IdOrTag
}

// GetIdOrTagOk returns a tuple with the IdOrTag field value
// and a boolean to check if the value has been set.
func (o *VersionRef) GetIdOrTagOk() (*VersionRefIdOrTag, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdOrTag, true
}

// SetIdOrTag sets field value
func (o *VersionRef) SetIdOrTag(v VersionRefIdOrTag) {
	o.IdOrTag = v
}

func (o VersionRef) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["definitionId"] = o.DefinitionId
	toSerialize["idOrTag"] = o.IdOrTag
	return toSerialize, nil
}

func (o *VersionRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"definitionId",
		"idOrTag",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVersionRef := _VersionRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varVersionRef)

	if err != nil {
		return err
	}

	*o = VersionRef(varVersionRef)

	return err
}

type NullableVersionRef struct {
	value *VersionRef
	isSet bool
}

func (v NullableVersionRef) Get() *VersionRef {
	return v.value
}

func (v *NullableVersionRef) Set(val *VersionRef) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionRef) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionRef(val *VersionRef) *NullableVersionRef {
	return &NullableVersionRef{value: val, isSet: true}
}

func (v NullableVersionRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
