/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TokenUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenUsage{}

// TokenUsage struct for TokenUsage
type TokenUsage struct {
	Input       int32        `json:"input"`
	InputCached int32        `json:"inputCached"`
	Output      int32        `json:"output"`
	Reasoning   int32        `json:"reasoning"`
	Total       int32        `json:"total"`
	ServiceTier *ServiceTier `json:"serviceTier,omitempty"`
}

type _TokenUsage TokenUsage

// NewTokenUsage instantiates a new TokenUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenUsage(input int32, inputCached int32, output int32, reasoning int32, total int32) *TokenUsage {
	this := TokenUsage{}
	this.Input = input
	this.InputCached = inputCached
	this.Output = output
	this.Reasoning = reasoning
	this.Total = total
	return &this
}

// NewTokenUsageWithDefaults instantiates a new TokenUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenUsageWithDefaults() *TokenUsage {
	this := TokenUsage{}
	return &this
}

// GetInput returns the Input field value
func (o *TokenUsage) GetInput() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *TokenUsage) GetInputOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *TokenUsage) SetInput(v int32) {
	o.Input = v
}

// GetInputCached returns the InputCached field value
func (o *TokenUsage) GetInputCached() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InputCached
}

// GetInputCachedOk returns a tuple with the InputCached field value
// and a boolean to check if the value has been set.
func (o *TokenUsage) GetInputCachedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InputCached, true
}

// SetInputCached sets field value
func (o *TokenUsage) SetInputCached(v int32) {
	o.InputCached = v
}

// GetOutput returns the Output field value
func (o *TokenUsage) GetOutput() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Output
}

// GetOutputOk returns a tuple with the Output field value
// and a boolean to check if the value has been set.
func (o *TokenUsage) GetOutputOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Output, true
}

// SetOutput sets field value
func (o *TokenUsage) SetOutput(v int32) {
	o.Output = v
}

// GetReasoning returns the Reasoning field value
func (o *TokenUsage) GetReasoning() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Reasoning
}

// GetReasoningOk returns a tuple with the Reasoning field value
// and a boolean to check if the value has been set.
func (o *TokenUsage) GetReasoningOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reasoning, true
}

// SetReasoning sets field value
func (o *TokenUsage) SetReasoning(v int32) {
	o.Reasoning = v
}

// GetTotal returns the Total field value
func (o *TokenUsage) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *TokenUsage) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *TokenUsage) SetTotal(v int32) {
	o.Total = v
}

// GetServiceTier returns the ServiceTier field value if set, zero value otherwise.
func (o *TokenUsage) GetServiceTier() ServiceTier {
	if o == nil || IsNil(o.ServiceTier) {
		var ret ServiceTier
		return ret
	}
	return *o.ServiceTier
}

// GetServiceTierOk returns a tuple with the ServiceTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenUsage) GetServiceTierOk() (*ServiceTier, bool) {
	if o == nil || IsNil(o.ServiceTier) {
		return nil, false
	}
	return o.ServiceTier, true
}

// HasServiceTier returns a boolean if a field has been set.
func (o *TokenUsage) HasServiceTier() bool {
	if o != nil && !IsNil(o.ServiceTier) {
		return true
	}

	return false
}

// SetServiceTier gets a reference to the given ServiceTier and assigns it to the ServiceTier field.
func (o *TokenUsage) SetServiceTier(v ServiceTier) {
	o.ServiceTier = &v
}

func (o TokenUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["input"] = o.Input
	toSerialize["inputCached"] = o.InputCached
	toSerialize["output"] = o.Output
	toSerialize["reasoning"] = o.Reasoning
	toSerialize["total"] = o.Total
	if !IsNil(o.ServiceTier) {
		toSerialize["serviceTier"] = o.ServiceTier
	}
	return toSerialize, nil
}

func (o *TokenUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input",
		"inputCached",
		"output",
		"reasoning",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenUsage := _TokenUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenUsage)

	if err != nil {
		return err
	}

	*o = TokenUsage(varTokenUsage)

	return err
}

type NullableTokenUsage struct {
	value *TokenUsage
	isSet bool
}

func (v NullableTokenUsage) Get() *TokenUsage {
	return v.value
}

func (v *NullableTokenUsage) Set(val *TokenUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenUsage(val *TokenUsage) *NullableTokenUsage {
	return &NullableTokenUsage{value: val, isSet: true}
}

func (v NullableTokenUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
