/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ModelCost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelCost{}

// ModelCost struct for ModelCost
type ModelCost struct {
	Input       float32         `json:"input"`
	CachedInput NullableFloat32 `json:"cachedInput,omitempty"`
	Output      float32         `json:"output"`
	WebSearch   *float32        `json:"webSearch,omitempty"`
	Total       float32         `json:"total"`
}

type _ModelCost ModelCost

// NewModelCost instantiates a new ModelCost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelCost(input float32, output float32, total float32) *ModelCost {
	this := ModelCost{}
	this.Input = input
	this.Output = output
	var webSearch float32 = 0
	this.WebSearch = &webSearch
	this.Total = total
	return &this
}

// NewModelCostWithDefaults instantiates a new ModelCost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelCostWithDefaults() *ModelCost {
	this := ModelCost{}
	var webSearch float32 = 0
	this.WebSearch = &webSearch
	return &this
}

// GetInput returns the Input field value
func (o *ModelCost) GetInput() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *ModelCost) GetInputOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *ModelCost) SetInput(v float32) {
	o.Input = v
}

// GetCachedInput returns the CachedInput field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelCost) GetCachedInput() float32 {
	if o == nil || IsNil(o.CachedInput.Get()) {
		var ret float32
		return ret
	}
	return *o.CachedInput.Get()
}

// GetCachedInputOk returns a tuple with the CachedInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelCost) GetCachedInputOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CachedInput.Get(), o.CachedInput.IsSet()
}

// HasCachedInput returns a boolean if a field has been set.
func (o *ModelCost) HasCachedInput() bool {
	if o != nil && o.CachedInput.IsSet() {
		return true
	}

	return false
}

// SetCachedInput gets a reference to the given NullableFloat32 and assigns it to the CachedInput field.
func (o *ModelCost) SetCachedInput(v float32) {
	o.CachedInput.Set(&v)
}

// SetCachedInputNil sets the value for CachedInput to be an explicit nil
func (o *ModelCost) SetCachedInputNil() {
	o.CachedInput.Set(nil)
}

// UnsetCachedInput ensures that no value is present for CachedInput, not even an explicit nil
func (o *ModelCost) UnsetCachedInput() {
	o.CachedInput.Unset()
}

// GetOutput returns the Output field value
func (o *ModelCost) GetOutput() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Output
}

// GetOutputOk returns a tuple with the Output field value
// and a boolean to check if the value has been set.
func (o *ModelCost) GetOutputOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Output, true
}

// SetOutput sets field value
func (o *ModelCost) SetOutput(v float32) {
	o.Output = v
}

// GetWebSearch returns the WebSearch field value if set, zero value otherwise.
func (o *ModelCost) GetWebSearch() float32 {
	if o == nil || IsNil(o.WebSearch) {
		var ret float32
		return ret
	}
	return *o.WebSearch
}

// GetWebSearchOk returns a tuple with the WebSearch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelCost) GetWebSearchOk() (*float32, bool) {
	if o == nil || IsNil(o.WebSearch) {
		return nil, false
	}
	return o.WebSearch, true
}

// HasWebSearch returns a boolean if a field has been set.
func (o *ModelCost) HasWebSearch() bool {
	if o != nil && !IsNil(o.WebSearch) {
		return true
	}

	return false
}

// SetWebSearch gets a reference to the given float32 and assigns it to the WebSearch field.
func (o *ModelCost) SetWebSearch(v float32) {
	o.WebSearch = &v
}

// GetTotal returns the Total field value
func (o *ModelCost) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ModelCost) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ModelCost) SetTotal(v float32) {
	o.Total = v
}

func (o ModelCost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelCost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["input"] = o.Input
	if o.CachedInput.IsSet() {
		toSerialize["cachedInput"] = o.CachedInput.Get()
	}
	toSerialize["output"] = o.Output
	if !IsNil(o.WebSearch) {
		toSerialize["webSearch"] = o.WebSearch
	}
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *ModelCost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input",
		"output",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelCost := _ModelCost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelCost)

	if err != nil {
		return err
	}

	*o = ModelCost(varModelCost)

	return err
}

type NullableModelCost struct {
	value *ModelCost
	isSet bool
}

func (v NullableModelCost) Get() *ModelCost {
	return v.value
}

func (v *NullableModelCost) Set(val *ModelCost) {
	v.value = val
	v.isSet = true
}

func (v NullableModelCost) IsSet() bool {
	return v.isSet
}

func (v *NullableModelCost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelCost(val *ModelCost) *NullableModelCost {
	return &NullableModelCost{value: val, isSet: true}
}

func (v NullableModelCost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelCost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
