/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// VersionRefIdOrTag - Revision ID or version number or tag.
type VersionRefIdOrTag struct {
	Int32  *int32
	String *string
}

// int32AsVersionRefIdOrTag is a convenience function that returns int32 wrapped in VersionRefIdOrTag
func Int32AsVersionRefIdOrTag(v *int32) VersionRefIdOrTag {
	return VersionRefIdOrTag{
		Int32: v,
	}
}

// stringAsVersionRefIdOrTag is a convenience function that returns string wrapped in VersionRefIdOrTag
func StringAsVersionRefIdOrTag(v *string) VersionRefIdOrTag {
	return VersionRefIdOrTag{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *VersionRefIdOrTag) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int32
	err = json.Unmarshal(data, &dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			match++
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(VersionRefIdOrTag)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(VersionRefIdOrTag)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VersionRefIdOrTag) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VersionRefIdOrTag) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj VersionRefIdOrTag) GetActualInstanceValue() interface{} {
	if obj.Int32 != nil {
		return *obj.Int32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableVersionRefIdOrTag struct {
	value *VersionRefIdOrTag
	isSet bool
}

func (v NullableVersionRefIdOrTag) Get() *VersionRefIdOrTag {
	return v.value
}

func (v *NullableVersionRefIdOrTag) Set(val *VersionRefIdOrTag) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionRefIdOrTag) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionRefIdOrTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionRefIdOrTag(val *VersionRefIdOrTag) *NullableVersionRefIdOrTag {
	return &NullableVersionRefIdOrTag{value: val, isSet: true}
}

func (v NullableVersionRefIdOrTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionRefIdOrTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
