/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the KnowledgeDocumentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgeDocumentResponse{}

// KnowledgeDocumentResponse Knowledge document
type KnowledgeDocumentResponse struct {
	// Document ID
	Id string `json:"id"`
	// Processing status
	Status KnowledgeDocumentStatus `json:"status"`
	// Original file name
	FileName string `json:"fileName"`
	// File size in bytes
	Bytes int32 `json:"bytes"`
	// Number of chunks extracted
	ChunkCount int32 `json:"chunkCount"`
}

type _KnowledgeDocumentResponse KnowledgeDocumentResponse

// NewKnowledgeDocumentResponse instantiates a new KnowledgeDocumentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgeDocumentResponse(id string, status KnowledgeDocumentStatus, fileName string, bytes int32, chunkCount int32) *KnowledgeDocumentResponse {
	this := KnowledgeDocumentResponse{}
	this.Id = id
	this.Status = status
	this.FileName = fileName
	this.Bytes = bytes
	this.ChunkCount = chunkCount
	return &this
}

// NewKnowledgeDocumentResponseWithDefaults instantiates a new KnowledgeDocumentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgeDocumentResponseWithDefaults() *KnowledgeDocumentResponse {
	this := KnowledgeDocumentResponse{}
	return &this
}

// GetId returns the Id field value
func (o *KnowledgeDocumentResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KnowledgeDocumentResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *KnowledgeDocumentResponse) GetStatus() KnowledgeDocumentStatus {
	if o == nil {
		var ret KnowledgeDocumentStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentResponse) GetStatusOk() (*KnowledgeDocumentStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *KnowledgeDocumentResponse) SetStatus(v KnowledgeDocumentStatus) {
	o.Status = v
}

// GetFileName returns the FileName field value
func (o *KnowledgeDocumentResponse) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentResponse) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *KnowledgeDocumentResponse) SetFileName(v string) {
	o.FileName = v
}

// GetBytes returns the Bytes field value
func (o *KnowledgeDocumentResponse) GetBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Bytes
}

// GetBytesOk returns a tuple with the Bytes field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentResponse) GetBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bytes, true
}

// SetBytes sets field value
func (o *KnowledgeDocumentResponse) SetBytes(v int32) {
	o.Bytes = v
}

// GetChunkCount returns the ChunkCount field value
func (o *KnowledgeDocumentResponse) GetChunkCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChunkCount
}

// GetChunkCountOk returns a tuple with the ChunkCount field value
// and a boolean to check if the value has been set.
func (o *KnowledgeDocumentResponse) GetChunkCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkCount, true
}

// SetChunkCount sets field value
func (o *KnowledgeDocumentResponse) SetChunkCount(v int32) {
	o.ChunkCount = v
}

func (o KnowledgeDocumentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgeDocumentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["fileName"] = o.FileName
	toSerialize["bytes"] = o.Bytes
	toSerialize["chunkCount"] = o.ChunkCount
	return toSerialize, nil
}

func (o *KnowledgeDocumentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"fileName",
		"bytes",
		"chunkCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgeDocumentResponse := _KnowledgeDocumentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varKnowledgeDocumentResponse)

	if err != nil {
		return err
	}

	*o = KnowledgeDocumentResponse(varKnowledgeDocumentResponse)

	return err
}

type NullableKnowledgeDocumentResponse struct {
	value *KnowledgeDocumentResponse
	isSet bool
}

func (v NullableKnowledgeDocumentResponse) Get() *KnowledgeDocumentResponse {
	return v.value
}

func (v *NullableKnowledgeDocumentResponse) Set(val *KnowledgeDocumentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeDocumentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeDocumentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeDocumentResponse(val *KnowledgeDocumentResponse) *NullableKnowledgeDocumentResponse {
	return &NullableKnowledgeDocumentResponse{value: val, isSet: true}
}

func (v NullableKnowledgeDocumentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeDocumentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
