/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the StreamTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamTokenResponse{}

// StreamTokenResponse A short-lived credential for subscribing to a thread's token stream.
type StreamTokenResponse struct {
	// Bearer token for the streaming endpoint. Safe to hand to a browser — it grants read access to this one thread and nothing else.
	Token string `json:"token"`
	// Timestamp when the token stops being accepted.
	ExpiresAt time.Time `json:"expiresAt"`
	// Fully-resolved SSE endpoint for this thread. Connect here with the token as a Bearer credential.
	Url string `json:"url"`
}

type _StreamTokenResponse StreamTokenResponse

// NewStreamTokenResponse instantiates a new StreamTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamTokenResponse(token string, expiresAt time.Time, url string) *StreamTokenResponse {
	this := StreamTokenResponse{}
	this.Token = token
	this.ExpiresAt = expiresAt
	this.Url = url
	return &this
}

// NewStreamTokenResponseWithDefaults instantiates a new StreamTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamTokenResponseWithDefaults() *StreamTokenResponse {
	this := StreamTokenResponse{}
	return &this
}

// GetToken returns the Token field value
func (o *StreamTokenResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *StreamTokenResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *StreamTokenResponse) SetToken(v string) {
	o.Token = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *StreamTokenResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *StreamTokenResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *StreamTokenResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetUrl returns the Url field value
func (o *StreamTokenResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *StreamTokenResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *StreamTokenResponse) SetUrl(v string) {
	o.Url = v
}

func (o StreamTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *StreamTokenResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
		"expiresAt",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStreamTokenResponse := _StreamTokenResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varStreamTokenResponse)

	if err != nil {
		return err
	}

	*o = StreamTokenResponse(varStreamTokenResponse)

	return err
}

type NullableStreamTokenResponse struct {
	value *StreamTokenResponse
	isSet bool
}

func (v NullableStreamTokenResponse) Get() *StreamTokenResponse {
	return v.value
}

func (v *NullableStreamTokenResponse) Set(val *StreamTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamTokenResponse(val *StreamTokenResponse) *NullableStreamTokenResponse {
	return &NullableStreamTokenResponse{value: val, isSet: true}
}

func (v NullableStreamTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
