/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelParams{}

// ModelParams AI model parameters.
type ModelParams struct {
	// Maximum completion tokens.
	MaxCompletionTokens NullableInt32 `json:"maxCompletionTokens,omitempty"`
	// Temperature.
	Temperature NullableFloat32 `json:"temperature,omitempty"`
	// Top P.
	TopP NullableFloat32 `json:"topP,omitempty"`
	// Verbosity.
	Verbosity NullableString `json:"verbosity,omitempty"`
	// Reasoning effort.
	ReasoningEffort NullableString `json:"reasoningEffort,omitempty"`
	// Return reasoning summary.
	ReasoningSummary NullableBool `json:"reasoningSummary,omitempty"`
	// Service tier.
	ServiceTier NullableServiceTier `json:"serviceTier,omitempty"`
}

// NewModelParams instantiates a new ModelParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelParams() *ModelParams {
	this := ModelParams{}
	return &this
}

// NewModelParamsWithDefaults instantiates a new ModelParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelParamsWithDefaults() *ModelParams {
	this := ModelParams{}
	return &this
}

// GetMaxCompletionTokens returns the MaxCompletionTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelParams) GetMaxCompletionTokens() int32 {
	if o == nil || IsNil(o.MaxCompletionTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxCompletionTokens.Get()
}

// GetMaxCompletionTokensOk returns a tuple with the MaxCompletionTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelParams) GetMaxCompletionTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxCompletionTokens.Get(), o.MaxCompletionTokens.IsSet()
}

// HasMaxCompletionTokens returns a boolean if a field has been set.
func (o *ModelParams) HasMaxCompletionTokens() bool {
	if o != nil && o.MaxCompletionTokens.IsSet() {
		return true
	}

	return false
}

// SetMaxCompletionTokens gets a reference to the given NullableInt32 and assigns it to the MaxCompletionTokens field.
func (o *ModelParams) SetMaxCompletionTokens(v int32) {
	o.MaxCompletionTokens.Set(&v)
}

// SetMaxCompletionTokensNil sets the value for MaxCompletionTokens to be an explicit nil
func (o *ModelParams) SetMaxCompletionTokensNil() {
	o.MaxCompletionTokens.Set(nil)
}

// UnsetMaxCompletionTokens ensures that no value is present for MaxCompletionTokens, not even an explicit nil
func (o *ModelParams) UnsetMaxCompletionTokens() {
	o.MaxCompletionTokens.Unset()
}

// GetTemperature returns the Temperature field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelParams) GetTemperature() float32 {
	if o == nil || IsNil(o.Temperature.Get()) {
		var ret float32
		return ret
	}
	return *o.Temperature.Get()
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelParams) GetTemperatureOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Temperature.Get(), o.Temperature.IsSet()
}

// HasTemperature returns a boolean if a field has been set.
func (o *ModelParams) HasTemperature() bool {
	if o != nil && o.Temperature.IsSet() {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given NullableFloat32 and assigns it to the Temperature field.
func (o *ModelParams) SetTemperature(v float32) {
	o.Temperature.Set(&v)
}

// SetTemperatureNil sets the value for Temperature to be an explicit nil
func (o *ModelParams) SetTemperatureNil() {
	o.Temperature.Set(nil)
}

// UnsetTemperature ensures that no value is present for Temperature, not even an explicit nil
func (o *ModelParams) UnsetTemperature() {
	o.Temperature.Unset()
}

// GetTopP returns the TopP field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelParams) GetTopP() float32 {
	if o == nil || IsNil(o.TopP.Get()) {
		var ret float32
		return ret
	}
	return *o.TopP.Get()
}

// GetTopPOk returns a tuple with the TopP field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelParams) GetTopPOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopP.Get(), o.TopP.IsSet()
}

// HasTopP returns a boolean if a field has been set.
func (o *ModelParams) HasTopP() bool {
	if o != nil && o.TopP.IsSet() {
		return true
	}

	return false
}

// SetTopP gets a reference to the given NullableFloat32 and assigns it to the TopP field.
func (o *ModelParams) SetTopP(v float32) {
	o.TopP.Set(&v)
}

// SetTopPNil sets the value for TopP to be an explicit nil
func (o *ModelParams) SetTopPNil() {
	o.TopP.Set(nil)
}

// UnsetTopP ensures that no value is present for TopP, not even an explicit nil
func (o *ModelParams) UnsetTopP() {
	o.TopP.Unset()
}

// GetVerbosity returns the Verbosity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelParams) GetVerbosity() string {
	if o == nil || IsNil(o.Verbosity.Get()) {
		var ret string
		return ret
	}
	return *o.Verbosity.Get()
}

// GetVerbosityOk returns a tuple with the Verbosity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelParams) GetVerbosityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Verbosity.Get(), o.Verbosity.IsSet()
}

// HasVerbosity returns a boolean if a field has been set.
func (o *ModelParams) HasVerbosity() bool {
	if o != nil && o.Verbosity.IsSet() {
		return true
	}

	return false
}

// SetVerbosity gets a reference to the given NullableString and assigns it to the Verbosity field.
func (o *ModelParams) SetVerbosity(v string) {
	o.Verbosity.Set(&v)
}

// SetVerbosityNil sets the value for Verbosity to be an explicit nil
func (o *ModelParams) SetVerbosityNil() {
	o.Verbosity.Set(nil)
}

// UnsetVerbosity ensures that no value is present for Verbosity, not even an explicit nil
func (o *ModelParams) UnsetVerbosity() {
	o.Verbosity.Unset()
}

// GetReasoningEffort returns the ReasoningEffort field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelParams) GetReasoningEffort() string {
	if o == nil || IsNil(o.ReasoningEffort.Get()) {
		var ret string
		return ret
	}
	return *o.ReasoningEffort.Get()
}

// GetReasoningEffortOk returns a tuple with the ReasoningEffort field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelParams) GetReasoningEffortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReasoningEffort.Get(), o.ReasoningEffort.IsSet()
}

// HasReasoningEffort returns a boolean if a field has been set.
func (o *ModelParams) HasReasoningEffort() bool {
	if o != nil && o.ReasoningEffort.IsSet() {
		return true
	}

	return false
}

// SetReasoningEffort gets a reference to the given NullableString and assigns it to the ReasoningEffort field.
func (o *ModelParams) SetReasoningEffort(v string) {
	o.ReasoningEffort.Set(&v)
}

// SetReasoningEffortNil sets the value for ReasoningEffort to be an explicit nil
func (o *ModelParams) SetReasoningEffortNil() {
	o.ReasoningEffort.Set(nil)
}

// UnsetReasoningEffort ensures that no value is present for ReasoningEffort, not even an explicit nil
func (o *ModelParams) UnsetReasoningEffort() {
	o.ReasoningEffort.Unset()
}

// GetReasoningSummary returns the ReasoningSummary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelParams) GetReasoningSummary() bool {
	if o == nil || IsNil(o.ReasoningSummary.Get()) {
		var ret bool
		return ret
	}
	return *o.ReasoningSummary.Get()
}

// GetReasoningSummaryOk returns a tuple with the ReasoningSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelParams) GetReasoningSummaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReasoningSummary.Get(), o.ReasoningSummary.IsSet()
}

// HasReasoningSummary returns a boolean if a field has been set.
func (o *ModelParams) HasReasoningSummary() bool {
	if o != nil && o.ReasoningSummary.IsSet() {
		return true
	}

	return false
}

// SetReasoningSummary gets a reference to the given NullableBool and assigns it to the ReasoningSummary field.
func (o *ModelParams) SetReasoningSummary(v bool) {
	o.ReasoningSummary.Set(&v)
}

// SetReasoningSummaryNil sets the value for ReasoningSummary to be an explicit nil
func (o *ModelParams) SetReasoningSummaryNil() {
	o.ReasoningSummary.Set(nil)
}

// UnsetReasoningSummary ensures that no value is present for ReasoningSummary, not even an explicit nil
func (o *ModelParams) UnsetReasoningSummary() {
	o.ReasoningSummary.Unset()
}

// GetServiceTier returns the ServiceTier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelParams) GetServiceTier() ServiceTier {
	if o == nil || IsNil(o.ServiceTier.Get()) {
		var ret ServiceTier
		return ret
	}
	return *o.ServiceTier.Get()
}

// GetServiceTierOk returns a tuple with the ServiceTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelParams) GetServiceTierOk() (*ServiceTier, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceTier.Get(), o.ServiceTier.IsSet()
}

// HasServiceTier returns a boolean if a field has been set.
func (o *ModelParams) HasServiceTier() bool {
	if o != nil && o.ServiceTier.IsSet() {
		return true
	}

	return false
}

// SetServiceTier gets a reference to the given NullableServiceTier and assigns it to the ServiceTier field.
func (o *ModelParams) SetServiceTier(v ServiceTier) {
	o.ServiceTier.Set(&v)
}

// SetServiceTierNil sets the value for ServiceTier to be an explicit nil
func (o *ModelParams) SetServiceTierNil() {
	o.ServiceTier.Set(nil)
}

// UnsetServiceTier ensures that no value is present for ServiceTier, not even an explicit nil
func (o *ModelParams) UnsetServiceTier() {
	o.ServiceTier.Unset()
}

func (o ModelParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MaxCompletionTokens.IsSet() {
		toSerialize["maxCompletionTokens"] = o.MaxCompletionTokens.Get()
	}
	if o.Temperature.IsSet() {
		toSerialize["temperature"] = o.Temperature.Get()
	}
	if o.TopP.IsSet() {
		toSerialize["topP"] = o.TopP.Get()
	}
	if o.Verbosity.IsSet() {
		toSerialize["verbosity"] = o.Verbosity.Get()
	}
	if o.ReasoningEffort.IsSet() {
		toSerialize["reasoningEffort"] = o.ReasoningEffort.Get()
	}
	if o.ReasoningSummary.IsSet() {
		toSerialize["reasoningSummary"] = o.ReasoningSummary.Get()
	}
	if o.ServiceTier.IsSet() {
		toSerialize["serviceTier"] = o.ServiceTier.Get()
	}
	return toSerialize, nil
}

type NullableModelParams struct {
	value *ModelParams
	isSet bool
}

func (v NullableModelParams) Get() *ModelParams {
	return v.value
}

func (v *NullableModelParams) Set(val *ModelParams) {
	v.value = val
	v.isSet = true
}

func (v NullableModelParams) IsSet() bool {
	return v.isSet
}

func (v *NullableModelParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelParams(val *ModelParams) *NullableModelParams {
	return &NullableModelParams{value: val, isSet: true}
}

func (v NullableModelParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
