/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// Memory the model 'Memory'
type Memory string

// List of Memory
const (
	MEMORY_STATELESS  Memory = "stateless"
	MEMORY_READ_ONLY  Memory = "read_only"
	MEMORY_READ_WRITE Memory = "read_write"
	MEMORY_WRITE_ONLY Memory = "write_only"
)

// All allowed values of Memory enum
var AllowedMemoryEnumValues = []Memory{
	"stateless",
	"read_only",
	"read_write",
	"write_only",
}

func (v *Memory) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Memory(value)
	for _, existing := range AllowedMemoryEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Memory", value)
}

// NewMemoryFromValue returns a pointer to a valid Memory
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMemoryFromValue(v string) (*Memory, error) {
	ev := Memory(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Memory: valid values are %v", v, AllowedMemoryEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Memory) IsValid() bool {
	for _, existing := range AllowedMemoryEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Memory value
func (v Memory) Ptr() *Memory {
	return &v
}

type NullableMemory struct {
	value *Memory
	isSet bool
}

func (v NullableMemory) Get() *Memory {
	return v.value
}

func (v *NullableMemory) Set(val *Memory) {
	v.value = val
	v.isSet = true
}

func (v NullableMemory) IsSet() bool {
	return v.isSet
}

func (v *NullableMemory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemory(val *Memory) *NullableMemory {
	return &NullableMemory{value: val, isSet: true}
}

func (v NullableMemory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
