/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateWorkflowRun type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkflowRun{}

// CreateWorkflowRun Request payload for creating a workflow run.
type CreateWorkflowRun struct {
	// Key-value map of input variable names to their values.
	Inputs map[string]string `json:"inputs"`
	// Thread ID to continue a multi-turn conversation. Omit to start a new thread.
	Thread NullableString `json:"thread,omitempty"`
	// Processing priority.
	Priority *string `json:"priority,omitempty"`
	// Environment that scopes which webhooks fire and which environment variables the run can access. Uses the default environment when omitted.
	Environment NullableString `json:"environment,omitempty"`
	// Runtime environment variable overrides for this run. Keys must be UPPER_CASE. At most 50 entries, 64 KB total.
	EnvVars map[string]string `json:"envVars,omitempty"`
	// Arbitrary key-value metadata attached to the run. Values can be strings or arrays of strings.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _CreateWorkflowRun CreateWorkflowRun

// NewCreateWorkflowRun instantiates a new CreateWorkflowRun object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkflowRun(inputs map[string]string) *CreateWorkflowRun {
	this := CreateWorkflowRun{}
	this.Inputs = inputs
	var priority string = "normal"
	this.Priority = &priority
	return &this
}

// NewCreateWorkflowRunWithDefaults instantiates a new CreateWorkflowRun object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkflowRunWithDefaults() *CreateWorkflowRun {
	this := CreateWorkflowRun{}
	var priority string = "normal"
	this.Priority = &priority
	return &this
}

// GetInputs returns the Inputs field value
func (o *CreateWorkflowRun) GetInputs() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRun) GetInputsOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Inputs, true
}

// SetInputs sets field value
func (o *CreateWorkflowRun) SetInputs(v map[string]string) {
	o.Inputs = v
}

// GetThread returns the Thread field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkflowRun) GetThread() string {
	if o == nil || IsNil(o.Thread.Get()) {
		var ret string
		return ret
	}
	return *o.Thread.Get()
}

// GetThreadOk returns a tuple with the Thread field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkflowRun) GetThreadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Thread.Get(), o.Thread.IsSet()
}

// HasThread returns a boolean if a field has been set.
func (o *CreateWorkflowRun) HasThread() bool {
	if o != nil && o.Thread.IsSet() {
		return true
	}

	return false
}

// SetThread gets a reference to the given NullableString and assigns it to the Thread field.
func (o *CreateWorkflowRun) SetThread(v string) {
	o.Thread.Set(&v)
}

// SetThreadNil sets the value for Thread to be an explicit nil
func (o *CreateWorkflowRun) SetThreadNil() {
	o.Thread.Set(nil)
}

// UnsetThread ensures that no value is present for Thread, not even an explicit nil
func (o *CreateWorkflowRun) UnsetThread() {
	o.Thread.Unset()
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *CreateWorkflowRun) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRun) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *CreateWorkflowRun) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *CreateWorkflowRun) SetPriority(v string) {
	o.Priority = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkflowRun) GetEnvironment() string {
	if o == nil || IsNil(o.Environment.Get()) {
		var ret string
		return ret
	}
	return *o.Environment.Get()
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkflowRun) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environment.Get(), o.Environment.IsSet()
}

// HasEnvironment returns a boolean if a field has been set.
func (o *CreateWorkflowRun) HasEnvironment() bool {
	if o != nil && o.Environment.IsSet() {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given NullableString and assigns it to the Environment field.
func (o *CreateWorkflowRun) SetEnvironment(v string) {
	o.Environment.Set(&v)
}

// SetEnvironmentNil sets the value for Environment to be an explicit nil
func (o *CreateWorkflowRun) SetEnvironmentNil() {
	o.Environment.Set(nil)
}

// UnsetEnvironment ensures that no value is present for Environment, not even an explicit nil
func (o *CreateWorkflowRun) UnsetEnvironment() {
	o.Environment.Unset()
}

// GetEnvVars returns the EnvVars field value if set, zero value otherwise.
func (o *CreateWorkflowRun) GetEnvVars() map[string]string {
	if o == nil || IsNil(o.EnvVars) {
		var ret map[string]string
		return ret
	}
	return o.EnvVars
}

// GetEnvVarsOk returns a tuple with the EnvVars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRun) GetEnvVarsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.EnvVars) {
		return map[string]string{}, false
	}
	return o.EnvVars, true
}

// HasEnvVars returns a boolean if a field has been set.
func (o *CreateWorkflowRun) HasEnvVars() bool {
	if o != nil && !IsNil(o.EnvVars) {
		return true
	}

	return false
}

// SetEnvVars gets a reference to the given map[string]string and assigns it to the EnvVars field.
func (o *CreateWorkflowRun) SetEnvVars(v map[string]string) {
	o.EnvVars = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateWorkflowRun) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRun) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateWorkflowRun) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CreateWorkflowRun) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o CreateWorkflowRun) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkflowRun) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["inputs"] = o.Inputs
	if o.Thread.IsSet() {
		toSerialize["thread"] = o.Thread.Get()
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if o.Environment.IsSet() {
		toSerialize["environment"] = o.Environment.Get()
	}
	if !IsNil(o.EnvVars) {
		toSerialize["envVars"] = o.EnvVars
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *CreateWorkflowRun) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inputs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWorkflowRun := _CreateWorkflowRun{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWorkflowRun)

	if err != nil {
		return err
	}

	*o = CreateWorkflowRun(varCreateWorkflowRun)

	return err
}

type NullableCreateWorkflowRun struct {
	value *CreateWorkflowRun
	isSet bool
}

func (v NullableCreateWorkflowRun) Get() *CreateWorkflowRun {
	return v.value
}

func (v *NullableCreateWorkflowRun) Set(val *CreateWorkflowRun) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkflowRun) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkflowRun) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkflowRun(val *CreateWorkflowRun) *NullableCreateWorkflowRun {
	return &NullableCreateWorkflowRun{value: val, isSet: true}
}

func (v NullableCreateWorkflowRun) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkflowRun) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
