/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// KnowledgeBaseStatus the model 'KnowledgeBaseStatus'
type KnowledgeBaseStatus string

// List of KnowledgeBaseStatus
const (
	KNOWLEDGEBASESTATUS_PENDING KnowledgeBaseStatus = "pending"
	KNOWLEDGEBASESTATUS_READY   KnowledgeBaseStatus = "ready"
	KNOWLEDGEBASESTATUS_FAILED  KnowledgeBaseStatus = "failed"
)

// All allowed values of KnowledgeBaseStatus enum
var AllowedKnowledgeBaseStatusEnumValues = []KnowledgeBaseStatus{
	"pending",
	"ready",
	"failed",
}

func (v *KnowledgeBaseStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := KnowledgeBaseStatus(value)
	for _, existing := range AllowedKnowledgeBaseStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid KnowledgeBaseStatus", value)
}

// NewKnowledgeBaseStatusFromValue returns a pointer to a valid KnowledgeBaseStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewKnowledgeBaseStatusFromValue(v string) (*KnowledgeBaseStatus, error) {
	ev := KnowledgeBaseStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for KnowledgeBaseStatus: valid values are %v", v, AllowedKnowledgeBaseStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v KnowledgeBaseStatus) IsValid() bool {
	for _, existing := range AllowedKnowledgeBaseStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to KnowledgeBaseStatus value
func (v KnowledgeBaseStatus) Ptr() *KnowledgeBaseStatus {
	return &v
}

type NullableKnowledgeBaseStatus struct {
	value *KnowledgeBaseStatus
	isSet bool
}

func (v NullableKnowledgeBaseStatus) Get() *KnowledgeBaseStatus {
	return v.value
}

func (v *NullableKnowledgeBaseStatus) Set(val *KnowledgeBaseStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeBaseStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeBaseStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeBaseStatus(val *KnowledgeBaseStatus) *NullableKnowledgeBaseStatus {
	return &NullableKnowledgeBaseStatus{value: val, isSet: true}
}

func (v NullableKnowledgeBaseStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeBaseStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
