/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PromptRevision type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptRevision{}

// PromptRevision Prompt revision
type PromptRevision struct {
	// Prompt revision ID.
	Id string `json:"id"`
	// Prompt ID.
	PromptId string `json:"promptId"`
	// Memory mode.
	Memory Memory `json:"memory"`
	// AI provider.
	Provider Provider `json:"provider"`
	// AI model.
	Model Model `json:"model"`
	// Model parameters.
	ModelParams ModelParams `json:"modelParams"`
	// AI model response format.
	ResponseFormat ResponseFormat `json:"responseFormat"`
	// The system prompt.
	SystemInstruction NullableString `json:"systemInstruction,omitempty"`
	// User and assistant messages.
	Messages []ContentMessageResponse `json:"messages"`
	// Available tools.
	Tools []Tool `json:"tools"`
}

type _PromptRevision PromptRevision

// NewPromptRevision instantiates a new PromptRevision object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptRevision(id string, promptId string, memory Memory, provider Provider, model Model, modelParams ModelParams, responseFormat ResponseFormat, messages []ContentMessageResponse, tools []Tool) *PromptRevision {
	this := PromptRevision{}
	this.Id = id
	this.PromptId = promptId
	this.Memory = memory
	this.Provider = provider
	this.Model = model
	this.ModelParams = modelParams
	this.ResponseFormat = responseFormat
	this.Messages = messages
	this.Tools = tools
	return &this
}

// NewPromptRevisionWithDefaults instantiates a new PromptRevision object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptRevisionWithDefaults() *PromptRevision {
	this := PromptRevision{}
	return &this
}

// GetId returns the Id field value
func (o *PromptRevision) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PromptRevision) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PromptRevision) SetId(v string) {
	o.Id = v
}

// GetPromptId returns the PromptId field value
func (o *PromptRevision) GetPromptId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PromptId
}

// GetPromptIdOk returns a tuple with the PromptId field value
// and a boolean to check if the value has been set.
func (o *PromptRevision) GetPromptIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromptId, true
}

// SetPromptId sets field value
func (o *PromptRevision) SetPromptId(v string) {
	o.PromptId = v
}

// GetMemory returns the Memory field value
func (o *PromptRevision) GetMemory() Memory {
	if o == nil {
		var ret Memory
		return ret
	}

	return o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value
// and a boolean to check if the value has been set.
func (o *PromptRevision) GetMemoryOk() (*Memory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memory, true
}

// SetMemory sets field value
func (o *PromptRevision) SetMemory(v Memory) {
	o.Memory = v
}

// GetProvider returns the Provider field value
func (o *PromptRevision) GetProvider() Provider {
	if o == nil {
		var ret Provider
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *PromptRevision) GetProviderOk() (*Provider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *PromptRevision) SetProvider(v Provider) {
	o.Provider = v
}

// GetModel returns the Model field value
func (o *PromptRevision) GetModel() Model {
	if o == nil {
		var ret Model
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *PromptRevision) GetModelOk() (*Model, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *PromptRevision) SetModel(v Model) {
	o.Model = v
}

// GetModelParams returns the ModelParams field value
func (o *PromptRevision) GetModelParams() ModelParams {
	if o == nil {
		var ret ModelParams
		return ret
	}

	return o.ModelParams
}

// GetModelParamsOk returns a tuple with the ModelParams field value
// and a boolean to check if the value has been set.
func (o *PromptRevision) GetModelParamsOk() (*ModelParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelParams, true
}

// SetModelParams sets field value
func (o *PromptRevision) SetModelParams(v ModelParams) {
	o.ModelParams = v
}

// GetResponseFormat returns the ResponseFormat field value
func (o *PromptRevision) GetResponseFormat() ResponseFormat {
	if o == nil {
		var ret ResponseFormat
		return ret
	}

	return o.ResponseFormat
}

// GetResponseFormatOk returns a tuple with the ResponseFormat field value
// and a boolean to check if the value has been set.
func (o *PromptRevision) GetResponseFormatOk() (*ResponseFormat, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseFormat, true
}

// SetResponseFormat sets field value
func (o *PromptRevision) SetResponseFormat(v ResponseFormat) {
	o.ResponseFormat = v
}

// GetSystemInstruction returns the SystemInstruction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptRevision) GetSystemInstruction() string {
	if o == nil || IsNil(o.SystemInstruction.Get()) {
		var ret string
		return ret
	}
	return *o.SystemInstruction.Get()
}

// GetSystemInstructionOk returns a tuple with the SystemInstruction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRevision) GetSystemInstructionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SystemInstruction.Get(), o.SystemInstruction.IsSet()
}

// HasSystemInstruction returns a boolean if a field has been set.
func (o *PromptRevision) HasSystemInstruction() bool {
	if o != nil && o.SystemInstruction.IsSet() {
		return true
	}

	return false
}

// SetSystemInstruction gets a reference to the given NullableString and assigns it to the SystemInstruction field.
func (o *PromptRevision) SetSystemInstruction(v string) {
	o.SystemInstruction.Set(&v)
}

// SetSystemInstructionNil sets the value for SystemInstruction to be an explicit nil
func (o *PromptRevision) SetSystemInstructionNil() {
	o.SystemInstruction.Set(nil)
}

// UnsetSystemInstruction ensures that no value is present for SystemInstruction, not even an explicit nil
func (o *PromptRevision) UnsetSystemInstruction() {
	o.SystemInstruction.Unset()
}

// GetMessages returns the Messages field value
func (o *PromptRevision) GetMessages() []ContentMessageResponse {
	if o == nil {
		var ret []ContentMessageResponse
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *PromptRevision) GetMessagesOk() ([]ContentMessageResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *PromptRevision) SetMessages(v []ContentMessageResponse) {
	o.Messages = v
}

// GetTools returns the Tools field value
func (o *PromptRevision) GetTools() []Tool {
	if o == nil {
		var ret []Tool
		return ret
	}

	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value
// and a boolean to check if the value has been set.
func (o *PromptRevision) GetToolsOk() ([]Tool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tools, true
}

// SetTools sets field value
func (o *PromptRevision) SetTools(v []Tool) {
	o.Tools = v
}

func (o PromptRevision) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptRevision) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["promptId"] = o.PromptId
	toSerialize["memory"] = o.Memory
	toSerialize["provider"] = o.Provider
	toSerialize["model"] = o.Model
	toSerialize["modelParams"] = o.ModelParams
	toSerialize["responseFormat"] = o.ResponseFormat
	if o.SystemInstruction.IsSet() {
		toSerialize["systemInstruction"] = o.SystemInstruction.Get()
	}
	toSerialize["messages"] = o.Messages
	toSerialize["tools"] = o.Tools
	return toSerialize, nil
}

func (o *PromptRevision) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"promptId",
		"memory",
		"provider",
		"model",
		"modelParams",
		"responseFormat",
		"messages",
		"tools",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptRevision := _PromptRevision{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varPromptRevision)

	if err != nil {
		return err
	}

	*o = PromptRevision(varPromptRevision)

	return err
}

type NullablePromptRevision struct {
	value *PromptRevision
	isSet bool
}

func (v NullablePromptRevision) Get() *PromptRevision {
	return v.value
}

func (v *NullablePromptRevision) Set(val *PromptRevision) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptRevision) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptRevision) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptRevision(val *PromptRevision) *NullablePromptRevision {
	return &NullablePromptRevision{value: val, isSet: true}
}

func (v NullablePromptRevision) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptRevision) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
