/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// RunStatus the model 'RunStatus'
type RunStatus string

// List of RunStatus
const (
	RUNSTATUS_PENDING   RunStatus = "pending"
	RUNSTATUS_COMPLETED RunStatus = "completed"
	RUNSTATUS_FAILED    RunStatus = "failed"
)

// All allowed values of RunStatus enum
var AllowedRunStatusEnumValues = []RunStatus{
	"pending",
	"completed",
	"failed",
}

func (v *RunStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	// Keep a value newer than this SDK; IsValid reports whether the SDK lists it.
	*v = RunStatus(value)
	return nil
}

// NewRunStatusFromValue returns a pointer to a valid RunStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRunStatusFromValue(v string) (*RunStatus, error) {
	ev := RunStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RunStatus: valid values are %v", v, AllowedRunStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RunStatus) IsValid() bool {
	for _, existing := range AllowedRunStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RunStatus value
func (v RunStatus) Ptr() *RunStatus {
	return &v
}

type NullableRunStatus struct {
	value *RunStatus
	isSet bool
}

func (v NullableRunStatus) Get() *RunStatus {
	return v.value
}

func (v *NullableRunStatus) Set(val *RunStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRunStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRunStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunStatus(val *RunStatus) *NullableRunStatus {
	return &NullableRunStatus{value: val, isSet: true}
}

func (v NullableRunStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
