/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TextFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TextFormat{}

// TextFormat Text response format.
type TextFormat struct {
	Type string `json:"type"`
}

type _TextFormat TextFormat

// NewTextFormat instantiates a new TextFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextFormat(type_ string) *TextFormat {
	this := TextFormat{}
	this.Type = type_
	return &this
}

// NewTextFormatWithDefaults instantiates a new TextFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextFormatWithDefaults() *TextFormat {
	this := TextFormat{}
	return &this
}

// GetType returns the Type field value
func (o *TextFormat) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TextFormat) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TextFormat) SetType(v string) {
	o.Type = v
}

func (o TextFormat) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TextFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TextFormat) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTextFormat := _TextFormat{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTextFormat)

	if err != nil {
		return err
	}

	*o = TextFormat(varTextFormat)

	return err
}

type NullableTextFormat struct {
	value *TextFormat
	isSet bool
}

func (v NullableTextFormat) Get() *TextFormat {
	return v.value
}

func (v *NullableTextFormat) Set(val *TextFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableTextFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableTextFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextFormat(val *TextFormat) *NullableTextFormat {
	return &NullableTextFormat{value: val, isSet: true}
}

func (v NullableTextFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
