/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EmittedItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmittedItem{}

// EmittedItem One emit-tool call: the tool name and its schema-validated payload.
type EmittedItem struct {
	// The emit tool that produced this payload.
	Tool string `json:"tool"`
	// The payload — the tool-call arguments, verbatim.
	Payload map[string]interface{} `json:"payload"`
}

type _EmittedItem EmittedItem

// NewEmittedItem instantiates a new EmittedItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmittedItem(tool string, payload map[string]interface{}) *EmittedItem {
	this := EmittedItem{}
	this.Tool = tool
	this.Payload = payload
	return &this
}

// NewEmittedItemWithDefaults instantiates a new EmittedItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmittedItemWithDefaults() *EmittedItem {
	this := EmittedItem{}
	return &this
}

// GetTool returns the Tool field value
func (o *EmittedItem) GetTool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tool
}

// GetToolOk returns a tuple with the Tool field value
// and a boolean to check if the value has been set.
func (o *EmittedItem) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tool, true
}

// SetTool sets field value
func (o *EmittedItem) SetTool(v string) {
	o.Tool = v
}

// GetPayload returns the Payload field value
func (o *EmittedItem) GetPayload() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *EmittedItem) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// SetPayload sets field value
func (o *EmittedItem) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

func (o EmittedItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmittedItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tool"] = o.Tool
	toSerialize["payload"] = o.Payload
	return toSerialize, nil
}

func (o *EmittedItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tool",
		"payload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmittedItem := _EmittedItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varEmittedItem)

	if err != nil {
		return err
	}

	*o = EmittedItem(varEmittedItem)

	return err
}

type NullableEmittedItem struct {
	value *EmittedItem
	isSet bool
}

func (v NullableEmittedItem) Get() *EmittedItem {
	return v.value
}

func (v *NullableEmittedItem) Set(val *EmittedItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEmittedItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEmittedItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmittedItem(val *EmittedItem) *NullableEmittedItem {
	return &NullableEmittedItem{value: val, isSet: true}
}

func (v NullableEmittedItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmittedItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
