/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HttpCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpCall{}

// HttpCall External HTTP call tool.
type HttpCall struct {
	// JSON schema of the parameters this tool expects.
	ParamsSchema string `json:"paramsSchema"`
	// The URL to call. Can contain ${ENV_VAR} and {{inputName}} placeholders.
	Url    string `json:"url"`
	Method string `json:"method"`
	// The headers to send with the HTTP request. Can contain ${ENV_VAR} and {{inputName}} placeholders.
	Headers []HttpHeader `json:"headers,omitempty"`
	// The tool’s name.
	Name string `json:"name" validate:"regexp=[a-zA-Z0-9_-]+"`
	// The tool’s description.
	Description NullableString `json:"description,omitempty"`
	// Whether to stop processing if a tool call fails.
	FailFast bool   `json:"failFast"`
	Type     string `json:"type"`
}

type _HttpCall HttpCall

// NewHttpCall instantiates a new HttpCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpCall(paramsSchema string, url string, method string, name string, failFast bool, type_ string) *HttpCall {
	this := HttpCall{}
	this.ParamsSchema = paramsSchema
	this.Url = url
	this.Method = method
	this.Name = name
	this.FailFast = failFast
	this.Type = type_
	return &this
}

// NewHttpCallWithDefaults instantiates a new HttpCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpCallWithDefaults() *HttpCall {
	this := HttpCall{}
	return &this
}

// GetParamsSchema returns the ParamsSchema field value
func (o *HttpCall) GetParamsSchema() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParamsSchema
}

// GetParamsSchemaOk returns a tuple with the ParamsSchema field value
// and a boolean to check if the value has been set.
func (o *HttpCall) GetParamsSchemaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParamsSchema, true
}

// SetParamsSchema sets field value
func (o *HttpCall) SetParamsSchema(v string) {
	o.ParamsSchema = v
}

// GetUrl returns the Url field value
func (o *HttpCall) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *HttpCall) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *HttpCall) SetUrl(v string) {
	o.Url = v
}

// GetMethod returns the Method field value
func (o *HttpCall) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *HttpCall) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *HttpCall) SetMethod(v string) {
	o.Method = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *HttpCall) GetHeaders() []HttpHeader {
	if o == nil || IsNil(o.Headers) {
		var ret []HttpHeader
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpCall) GetHeadersOk() ([]HttpHeader, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *HttpCall) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []HttpHeader and assigns it to the Headers field.
func (o *HttpCall) SetHeaders(v []HttpHeader) {
	o.Headers = v
}

// GetName returns the Name field value
func (o *HttpCall) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HttpCall) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HttpCall) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HttpCall) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HttpCall) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *HttpCall) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *HttpCall) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *HttpCall) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *HttpCall) UnsetDescription() {
	o.Description.Unset()
}

// GetFailFast returns the FailFast field value
func (o *HttpCall) GetFailFast() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FailFast
}

// GetFailFastOk returns a tuple with the FailFast field value
// and a boolean to check if the value has been set.
func (o *HttpCall) GetFailFastOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailFast, true
}

// SetFailFast sets field value
func (o *HttpCall) SetFailFast(v bool) {
	o.FailFast = v
}

// GetType returns the Type field value
func (o *HttpCall) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *HttpCall) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *HttpCall) SetType(v string) {
	o.Type = v
}

func (o HttpCall) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["paramsSchema"] = o.ParamsSchema
	toSerialize["url"] = o.Url
	toSerialize["method"] = o.Method
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["failFast"] = o.FailFast
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *HttpCall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"paramsSchema",
		"url",
		"method",
		"name",
		"failFast",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHttpCall := _HttpCall{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHttpCall)

	if err != nil {
		return err
	}

	*o = HttpCall(varHttpCall)

	return err
}

type NullableHttpCall struct {
	value *HttpCall
	isSet bool
}

func (v NullableHttpCall) Get() *HttpCall {
	return v.value
}

func (v *NullableHttpCall) Set(val *HttpCall) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpCall) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpCall(val *HttpCall) *NullableHttpCall {
	return &NullableHttpCall{value: val, isSet: true}
}

func (v NullableHttpCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
