/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Mcp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Mcp{}

// Mcp Built-in MCP server tool.
type Mcp struct {
	// The MCP server tool’s name.
	Name string `json:"name" validate:"regexp=[a-zA-Z0-9_-]+"`
	// The URL of the MCP server.
	Url string `json:"url"`
	// Authorization token for the MCP server.
	AuthorizationToken NullableString `json:"authorizationToken,omitempty"`
	// Tool names the model may call. Empty or omitted allows all of the server’s tools.
	AllowedTools []string `json:"allowedTools,omitempty"`
	Type         string   `json:"type"`
}

type _Mcp Mcp

// NewMcp instantiates a new Mcp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcp(name string, url string, type_ string) *Mcp {
	this := Mcp{}
	this.Name = name
	this.Url = url
	this.Type = type_
	return &this
}

// NewMcpWithDefaults instantiates a new Mcp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcpWithDefaults() *Mcp {
	this := Mcp{}
	return &this
}

// GetName returns the Name field value
func (o *Mcp) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Mcp) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Mcp) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *Mcp) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *Mcp) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *Mcp) SetUrl(v string) {
	o.Url = v
}

// GetAuthorizationToken returns the AuthorizationToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Mcp) GetAuthorizationToken() string {
	if o == nil || IsNil(o.AuthorizationToken.Get()) {
		var ret string
		return ret
	}
	return *o.AuthorizationToken.Get()
}

// GetAuthorizationTokenOk returns a tuple with the AuthorizationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Mcp) GetAuthorizationTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthorizationToken.Get(), o.AuthorizationToken.IsSet()
}

// HasAuthorizationToken returns a boolean if a field has been set.
func (o *Mcp) HasAuthorizationToken() bool {
	if o != nil && o.AuthorizationToken.IsSet() {
		return true
	}

	return false
}

// SetAuthorizationToken gets a reference to the given NullableString and assigns it to the AuthorizationToken field.
func (o *Mcp) SetAuthorizationToken(v string) {
	o.AuthorizationToken.Set(&v)
}

// SetAuthorizationTokenNil sets the value for AuthorizationToken to be an explicit nil
func (o *Mcp) SetAuthorizationTokenNil() {
	o.AuthorizationToken.Set(nil)
}

// UnsetAuthorizationToken ensures that no value is present for AuthorizationToken, not even an explicit nil
func (o *Mcp) UnsetAuthorizationToken() {
	o.AuthorizationToken.Unset()
}

// GetAllowedTools returns the AllowedTools field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Mcp) GetAllowedTools() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedTools
}

// GetAllowedToolsOk returns a tuple with the AllowedTools field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Mcp) GetAllowedToolsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedTools) {
		return nil, false
	}
	return o.AllowedTools, true
}

// HasAllowedTools returns a boolean if a field has been set.
func (o *Mcp) HasAllowedTools() bool {
	if o != nil && !IsNil(o.AllowedTools) {
		return true
	}

	return false
}

// SetAllowedTools gets a reference to the given []string and assigns it to the AllowedTools field.
func (o *Mcp) SetAllowedTools(v []string) {
	o.AllowedTools = v
}

// GetType returns the Type field value
func (o *Mcp) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Mcp) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Mcp) SetType(v string) {
	o.Type = v
}

func (o Mcp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Mcp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	if o.AuthorizationToken.IsSet() {
		toSerialize["authorizationToken"] = o.AuthorizationToken.Get()
	}
	if o.AllowedTools != nil {
		toSerialize["allowedTools"] = o.AllowedTools
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *Mcp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMcp := _Mcp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varMcp)

	if err != nil {
		return err
	}

	*o = Mcp(varMcp)

	return err
}

type NullableMcp struct {
	value *Mcp
	isSet bool
}

func (v NullableMcp) Get() *Mcp {
	return v.value
}

func (v *NullableMcp) Set(val *Mcp) {
	v.value = val
	v.isSet = true
}

func (v NullableMcp) IsSet() bool {
	return v.isSet
}

func (v *NullableMcp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcp(val *Mcp) *NullableMcp {
	return &NullableMcp{value: val, isSet: true}
}

func (v NullableMcp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
