/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the JsonSchemaFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonSchemaFormat{}

// JsonSchemaFormat JSON schema response format.
type JsonSchemaFormat struct {
	// Schema name.
	Name string `json:"name" validate:"regexp=[a-zA-Z0-9_-]+"`
	// The JSON schema as string.
	Schema string `json:"schema"`
	// Whether the model should follow the schema strictly.
	Strict NullableBool `json:"strict,omitempty"`
	// Schema description.
	Description NullableString `json:"description,omitempty"`
	Type        string         `json:"type"`
}

type _JsonSchemaFormat JsonSchemaFormat

// NewJsonSchemaFormat instantiates a new JsonSchemaFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonSchemaFormat(name string, schema string, type_ string) *JsonSchemaFormat {
	this := JsonSchemaFormat{}
	this.Name = name
	this.Schema = schema
	var strict bool = false
	this.Strict = *NewNullableBool(&strict)
	this.Type = type_
	return &this
}

// NewJsonSchemaFormatWithDefaults instantiates a new JsonSchemaFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonSchemaFormatWithDefaults() *JsonSchemaFormat {
	this := JsonSchemaFormat{}
	var strict bool = false
	this.Strict = *NewNullableBool(&strict)
	return &this
}

// GetName returns the Name field value
func (o *JsonSchemaFormat) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *JsonSchemaFormat) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *JsonSchemaFormat) SetName(v string) {
	o.Name = v
}

// GetSchema returns the Schema field value
func (o *JsonSchemaFormat) GetSchema() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *JsonSchemaFormat) GetSchemaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *JsonSchemaFormat) SetSchema(v string) {
	o.Schema = v
}

// GetStrict returns the Strict field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JsonSchemaFormat) GetStrict() bool {
	if o == nil || IsNil(o.Strict.Get()) {
		var ret bool
		return ret
	}
	return *o.Strict.Get()
}

// GetStrictOk returns a tuple with the Strict field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JsonSchemaFormat) GetStrictOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Strict.Get(), o.Strict.IsSet()
}

// HasStrict returns a boolean if a field has been set.
func (o *JsonSchemaFormat) HasStrict() bool {
	if o != nil && o.Strict.IsSet() {
		return true
	}

	return false
}

// SetStrict gets a reference to the given NullableBool and assigns it to the Strict field.
func (o *JsonSchemaFormat) SetStrict(v bool) {
	o.Strict.Set(&v)
}

// SetStrictNil sets the value for Strict to be an explicit nil
func (o *JsonSchemaFormat) SetStrictNil() {
	o.Strict.Set(nil)
}

// UnsetStrict ensures that no value is present for Strict, not even an explicit nil
func (o *JsonSchemaFormat) UnsetStrict() {
	o.Strict.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JsonSchemaFormat) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JsonSchemaFormat) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *JsonSchemaFormat) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *JsonSchemaFormat) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *JsonSchemaFormat) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *JsonSchemaFormat) UnsetDescription() {
	o.Description.Unset()
}

// GetType returns the Type field value
func (o *JsonSchemaFormat) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *JsonSchemaFormat) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *JsonSchemaFormat) SetType(v string) {
	o.Type = v
}

func (o JsonSchemaFormat) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonSchemaFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["schema"] = o.Schema
	if o.Strict.IsSet() {
		toSerialize["strict"] = o.Strict.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *JsonSchemaFormat) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"schema",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJsonSchemaFormat := _JsonSchemaFormat{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varJsonSchemaFormat)

	if err != nil {
		return err
	}

	*o = JsonSchemaFormat(varJsonSchemaFormat)

	return err
}

type NullableJsonSchemaFormat struct {
	value *JsonSchemaFormat
	isSet bool
}

func (v NullableJsonSchemaFormat) Get() *JsonSchemaFormat {
	return v.value
}

func (v *NullableJsonSchemaFormat) Set(val *JsonSchemaFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonSchemaFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonSchemaFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonSchemaFormat(val *JsonSchemaFormat) *NullableJsonSchemaFormat {
	return &NullableJsonSchemaFormat{value: val, isSet: true}
}

func (v NullableJsonSchemaFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonSchemaFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
