/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// TranscriptItem - struct for TranscriptItem
type TranscriptItem struct {
	TranscriptData *TranscriptData
	TranscriptText *TranscriptText
	TranscriptTool *TranscriptTool
}

// TranscriptDataAsTranscriptItem is a convenience function that returns TranscriptData wrapped in TranscriptItem
func TranscriptDataAsTranscriptItem(v *TranscriptData) TranscriptItem {
	return TranscriptItem{
		TranscriptData: v,
	}
}

// TranscriptTextAsTranscriptItem is a convenience function that returns TranscriptText wrapped in TranscriptItem
func TranscriptTextAsTranscriptItem(v *TranscriptText) TranscriptItem {
	return TranscriptItem{
		TranscriptText: v,
	}
}

// TranscriptToolAsTranscriptItem is a convenience function that returns TranscriptTool wrapped in TranscriptItem
func TranscriptToolAsTranscriptItem(v *TranscriptTool) TranscriptItem {
	return TranscriptItem{
		TranscriptTool: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *TranscriptItem) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'data'
	if jsonDict["type"] == "data" {
		// try to unmarshal JSON data into TranscriptData
		err = json.Unmarshal(data, &dst.TranscriptData)
		if err == nil {
			return nil // data stored in dst.TranscriptData, return on the first match
		} else {
			dst.TranscriptData = nil
			return fmt.Errorf("failed to unmarshal TranscriptItem as TranscriptData: %s", err.Error())
		}
	}

	// check if the discriminator value is 'text'
	if jsonDict["type"] == "text" {
		// try to unmarshal JSON data into TranscriptText
		err = json.Unmarshal(data, &dst.TranscriptText)
		if err == nil {
			return nil // data stored in dst.TranscriptText, return on the first match
		} else {
			dst.TranscriptText = nil
			return fmt.Errorf("failed to unmarshal TranscriptItem as TranscriptText: %s", err.Error())
		}
	}

	// check if the discriminator value is 'tool'
	if jsonDict["type"] == "tool" {
		// try to unmarshal JSON data into TranscriptTool
		err = json.Unmarshal(data, &dst.TranscriptTool)
		if err == nil {
			return nil // data stored in dst.TranscriptTool, return on the first match
		} else {
			dst.TranscriptTool = nil
			return fmt.Errorf("failed to unmarshal TranscriptItem as TranscriptTool: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TranscriptItem) MarshalJSON() ([]byte, error) {
	if src.TranscriptData != nil {
		return json.Marshal(&src.TranscriptData)
	}

	if src.TranscriptText != nil {
		return json.Marshal(&src.TranscriptText)
	}

	if src.TranscriptTool != nil {
		return json.Marshal(&src.TranscriptTool)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TranscriptItem) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.TranscriptData != nil {
		return obj.TranscriptData
	}

	if obj.TranscriptText != nil {
		return obj.TranscriptText
	}

	if obj.TranscriptTool != nil {
		return obj.TranscriptTool
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TranscriptItem) GetActualInstanceValue() interface{} {
	if obj.TranscriptData != nil {
		return *obj.TranscriptData
	}

	if obj.TranscriptText != nil {
		return *obj.TranscriptText
	}

	if obj.TranscriptTool != nil {
		return *obj.TranscriptTool
	}

	// all schemas are nil
	return nil
}

type NullableTranscriptItem struct {
	value *TranscriptItem
	isSet bool
}

func (v NullableTranscriptItem) Get() *TranscriptItem {
	return v.value
}

func (v *NullableTranscriptItem) Set(val *TranscriptItem) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscriptItem) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscriptItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscriptItem(val *TranscriptItem) *NullableTranscriptItem {
	return &NullableTranscriptItem{value: val, isSet: true}
}

func (v NullableTranscriptItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscriptItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
