/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the KnowledgeSearch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgeSearch{}

// KnowledgeSearch RAG tool to search knowledge base.
type KnowledgeSearch struct {
	KnowledgeBaseId string `json:"knowledgeBaseId"`
	// The tool’s name.
	Name string `json:"name" validate:"regexp=[a-zA-Z0-9_-]+"`
	// The tool’s description.
	Description NullableString `json:"description,omitempty"`
	// Whether to stop processing if a tool call fails.
	FailFast *bool  `json:"failFast,omitempty"`
	Type     string `json:"type"`
}

type _KnowledgeSearch KnowledgeSearch

// NewKnowledgeSearch instantiates a new KnowledgeSearch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgeSearch(knowledgeBaseId string, name string, type_ string) *KnowledgeSearch {
	this := KnowledgeSearch{}
	this.KnowledgeBaseId = knowledgeBaseId
	this.Name = name
	var failFast bool = false
	this.FailFast = &failFast
	this.Type = type_
	return &this
}

// NewKnowledgeSearchWithDefaults instantiates a new KnowledgeSearch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgeSearchWithDefaults() *KnowledgeSearch {
	this := KnowledgeSearch{}
	var failFast bool = false
	this.FailFast = &failFast
	return &this
}

// GetKnowledgeBaseId returns the KnowledgeBaseId field value
func (o *KnowledgeSearch) GetKnowledgeBaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KnowledgeBaseId
}

// GetKnowledgeBaseIdOk returns a tuple with the KnowledgeBaseId field value
// and a boolean to check if the value has been set.
func (o *KnowledgeSearch) GetKnowledgeBaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KnowledgeBaseId, true
}

// SetKnowledgeBaseId sets field value
func (o *KnowledgeSearch) SetKnowledgeBaseId(v string) {
	o.KnowledgeBaseId = v
}

// GetName returns the Name field value
func (o *KnowledgeSearch) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *KnowledgeSearch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *KnowledgeSearch) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KnowledgeSearch) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KnowledgeSearch) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *KnowledgeSearch) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *KnowledgeSearch) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *KnowledgeSearch) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *KnowledgeSearch) UnsetDescription() {
	o.Description.Unset()
}

// GetFailFast returns the FailFast field value if set, zero value otherwise.
func (o *KnowledgeSearch) GetFailFast() bool {
	if o == nil || IsNil(o.FailFast) {
		var ret bool
		return ret
	}
	return *o.FailFast
}

// GetFailFastOk returns a tuple with the FailFast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnowledgeSearch) GetFailFastOk() (*bool, bool) {
	if o == nil || IsNil(o.FailFast) {
		return nil, false
	}
	return o.FailFast, true
}

// HasFailFast returns a boolean if a field has been set.
func (o *KnowledgeSearch) HasFailFast() bool {
	if o != nil && !IsNil(o.FailFast) {
		return true
	}

	return false
}

// SetFailFast gets a reference to the given bool and assigns it to the FailFast field.
func (o *KnowledgeSearch) SetFailFast(v bool) {
	o.FailFast = &v
}

// GetType returns the Type field value
func (o *KnowledgeSearch) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *KnowledgeSearch) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *KnowledgeSearch) SetType(v string) {
	o.Type = v
}

func (o KnowledgeSearch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgeSearch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["knowledgeBaseId"] = o.KnowledgeBaseId
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.FailFast) {
		toSerialize["failFast"] = o.FailFast
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *KnowledgeSearch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"knowledgeBaseId",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgeSearch := _KnowledgeSearch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKnowledgeSearch)

	if err != nil {
		return err
	}

	*o = KnowledgeSearch(varKnowledgeSearch)

	return err
}

type NullableKnowledgeSearch struct {
	value *KnowledgeSearch
	isSet bool
}

func (v NullableKnowledgeSearch) Get() *KnowledgeSearch {
	return v.value
}

func (v *NullableKnowledgeSearch) Set(val *KnowledgeSearch) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeSearch) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeSearch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeSearch(val *KnowledgeSearch) *NullableKnowledgeSearch {
	return &NullableKnowledgeSearch{value: val, isSet: true}
}

func (v NullableKnowledgeSearch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeSearch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
