/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TranscriptTool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranscriptTool{}

// TranscriptTool A tool the model used: its name and how the call ended.
type TranscriptTool struct {
	// Tool name, as the model called it.
	Name string `json:"name"`
	// How the call ended.
	Status ToolStatus `json:"status"`
	// Search queries the model ran. Only ever populated by the built-in web_search tool.
	Queries []string `json:"queries"`
	// Sources this call returned. Only ever populated by the built-in web_search tool.
	Citations []Citation `json:"citations"`
	Type      string     `json:"type"`
}

type _TranscriptTool TranscriptTool

// NewTranscriptTool instantiates a new TranscriptTool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranscriptTool(name string, status ToolStatus, queries []string, citations []Citation, type_ string) *TranscriptTool {
	this := TranscriptTool{}
	this.Name = name
	this.Status = status
	this.Queries = queries
	this.Citations = citations
	this.Type = type_
	return &this
}

// NewTranscriptToolWithDefaults instantiates a new TranscriptTool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranscriptToolWithDefaults() *TranscriptTool {
	this := TranscriptTool{}
	return &this
}

// GetName returns the Name field value
func (o *TranscriptTool) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TranscriptTool) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TranscriptTool) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *TranscriptTool) GetStatus() ToolStatus {
	if o == nil {
		var ret ToolStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TranscriptTool) GetStatusOk() (*ToolStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TranscriptTool) SetStatus(v ToolStatus) {
	o.Status = v
}

// GetQueries returns the Queries field value
func (o *TranscriptTool) GetQueries() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Queries
}

// GetQueriesOk returns a tuple with the Queries field value
// and a boolean to check if the value has been set.
func (o *TranscriptTool) GetQueriesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Queries, true
}

// SetQueries sets field value
func (o *TranscriptTool) SetQueries(v []string) {
	o.Queries = v
}

// GetCitations returns the Citations field value
func (o *TranscriptTool) GetCitations() []Citation {
	if o == nil {
		var ret []Citation
		return ret
	}

	return o.Citations
}

// GetCitationsOk returns a tuple with the Citations field value
// and a boolean to check if the value has been set.
func (o *TranscriptTool) GetCitationsOk() ([]Citation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Citations, true
}

// SetCitations sets field value
func (o *TranscriptTool) SetCitations(v []Citation) {
	o.Citations = v
}

// GetType returns the Type field value
func (o *TranscriptTool) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TranscriptTool) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TranscriptTool) SetType(v string) {
	o.Type = v
}

func (o TranscriptTool) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranscriptTool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["queries"] = o.Queries
	toSerialize["citations"] = o.Citations
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TranscriptTool) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"status",
		"queries",
		"citations",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTranscriptTool := _TranscriptTool{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTranscriptTool)

	if err != nil {
		return err
	}

	*o = TranscriptTool(varTranscriptTool)

	return err
}

type NullableTranscriptTool struct {
	value *TranscriptTool
	isSet bool
}

func (v NullableTranscriptTool) Get() *TranscriptTool {
	return v.value
}

func (v *NullableTranscriptTool) Set(val *TranscriptTool) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscriptTool) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscriptTool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscriptTool(val *TranscriptTool) *NullableTranscriptTool {
	return &NullableTranscriptTool{value: val, isSet: true}
}

func (v NullableTranscriptTool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscriptTool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
