/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the JsonObjectFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonObjectFormat{}

// JsonObjectFormat JSON object response format.
type JsonObjectFormat struct {
	Type string `json:"type"`
}

type _JsonObjectFormat JsonObjectFormat

// NewJsonObjectFormat instantiates a new JsonObjectFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonObjectFormat(type_ string) *JsonObjectFormat {
	this := JsonObjectFormat{}
	this.Type = type_
	return &this
}

// NewJsonObjectFormatWithDefaults instantiates a new JsonObjectFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonObjectFormatWithDefaults() *JsonObjectFormat {
	this := JsonObjectFormat{}
	return &this
}

// GetType returns the Type field value
func (o *JsonObjectFormat) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *JsonObjectFormat) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *JsonObjectFormat) SetType(v string) {
	o.Type = v
}

func (o JsonObjectFormat) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonObjectFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *JsonObjectFormat) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJsonObjectFormat := _JsonObjectFormat{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJsonObjectFormat)

	if err != nil {
		return err
	}

	*o = JsonObjectFormat(varJsonObjectFormat)

	return err
}

type NullableJsonObjectFormat struct {
	value *JsonObjectFormat
	isSet bool
}

func (v NullableJsonObjectFormat) Get() *JsonObjectFormat {
	return v.value
}

func (v *NullableJsonObjectFormat) Set(val *JsonObjectFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonObjectFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonObjectFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonObjectFormat(val *JsonObjectFormat) *NullableJsonObjectFormat {
	return &NullableJsonObjectFormat{value: val, isSet: true}
}

func (v NullableJsonObjectFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonObjectFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
