/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// KnowledgeDocumentStatus the model 'KnowledgeDocumentStatus'
type KnowledgeDocumentStatus string

// List of KnowledgeDocumentStatus
const (
	KNOWLEDGEDOCUMENTSTATUS_PENDING KnowledgeDocumentStatus = "pending"
	KNOWLEDGEDOCUMENTSTATUS_SEALED  KnowledgeDocumentStatus = "sealed"
	KNOWLEDGEDOCUMENTSTATUS_READY   KnowledgeDocumentStatus = "ready"
	KNOWLEDGEDOCUMENTSTATUS_FAILED  KnowledgeDocumentStatus = "failed"
)

// All allowed values of KnowledgeDocumentStatus enum
var AllowedKnowledgeDocumentStatusEnumValues = []KnowledgeDocumentStatus{
	"pending",
	"sealed",
	"ready",
	"failed",
}

func (v *KnowledgeDocumentStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	// Keep a value newer than this SDK; IsValid reports whether the SDK lists it.
	*v = KnowledgeDocumentStatus(value)
	return nil
}

// NewKnowledgeDocumentStatusFromValue returns a pointer to a valid KnowledgeDocumentStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewKnowledgeDocumentStatusFromValue(v string) (*KnowledgeDocumentStatus, error) {
	ev := KnowledgeDocumentStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for KnowledgeDocumentStatus: valid values are %v", v, AllowedKnowledgeDocumentStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v KnowledgeDocumentStatus) IsValid() bool {
	for _, existing := range AllowedKnowledgeDocumentStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to KnowledgeDocumentStatus value
func (v KnowledgeDocumentStatus) Ptr() *KnowledgeDocumentStatus {
	return &v
}

type NullableKnowledgeDocumentStatus struct {
	value *KnowledgeDocumentStatus
	isSet bool
}

func (v NullableKnowledgeDocumentStatus) Get() *KnowledgeDocumentStatus {
	return v.value
}

func (v *NullableKnowledgeDocumentStatus) Set(val *KnowledgeDocumentStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeDocumentStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeDocumentStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeDocumentStatus(val *KnowledgeDocumentStatus) *NullableKnowledgeDocumentStatus {
	return &NullableKnowledgeDocumentStatus{value: val, isSet: true}
}

func (v NullableKnowledgeDocumentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeDocumentStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
