/*
PromptJuggler

PromptJuggler API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WebSearch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSearch{}

// WebSearch Built-in web search.
type WebSearch struct {
	AllowedDomains []string `json:"allowedDomains,omitempty"`
	Type           string   `json:"type"`
}

type _WebSearch WebSearch

// NewWebSearch instantiates a new WebSearch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSearch(type_ string) *WebSearch {
	this := WebSearch{}
	this.Type = type_
	return &this
}

// NewWebSearchWithDefaults instantiates a new WebSearch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSearchWithDefaults() *WebSearch {
	this := WebSearch{}
	return &this
}

// GetAllowedDomains returns the AllowedDomains field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebSearch) GetAllowedDomains() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedDomains
}

// GetAllowedDomainsOk returns a tuple with the AllowedDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebSearch) GetAllowedDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedDomains) {
		return nil, false
	}
	return o.AllowedDomains, true
}

// HasAllowedDomains returns a boolean if a field has been set.
func (o *WebSearch) HasAllowedDomains() bool {
	if o != nil && !IsNil(o.AllowedDomains) {
		return true
	}

	return false
}

// SetAllowedDomains gets a reference to the given []string and assigns it to the AllowedDomains field.
func (o *WebSearch) SetAllowedDomains(v []string) {
	o.AllowedDomains = v
}

// GetType returns the Type field value
func (o *WebSearch) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WebSearch) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WebSearch) SetType(v string) {
	o.Type = v
}

func (o WebSearch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSearch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowedDomains != nil {
		toSerialize["allowedDomains"] = o.AllowedDomains
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *WebSearch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebSearch := _WebSearch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varWebSearch)

	if err != nil {
		return err
	}

	*o = WebSearch(varWebSearch)

	return err
}

type NullableWebSearch struct {
	value *WebSearch
	isSet bool
}

func (v NullableWebSearch) Get() *WebSearch {
	return v.value
}

func (v *NullableWebSearch) Set(val *WebSearch) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSearch) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSearch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSearch(val *WebSearch) *NullableWebSearch {
	return &NullableWebSearch{value: val, isSet: true}
}

func (v NullableWebSearch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSearch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
